/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.informes;

import com.boquerontech.supermercadoboqueron.Inicio;
import com.boquerontech.supermercadoboqueron.clientes.Cliente;
import com.boquerontech.supermercadoboqueron.database.cliente.ClienteDAO;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author navas
 */
public class ConsultarClientes extends javax.swing.JPanel {

    private Inicio inicioInstance;
    
    // Variables para datos
    private List<Cliente> listaCompleta; 
    private int paginaActual = 1;
    private final int ITEMS_POR_PAGINA = 8; 

    /**
     * Creates new form ConsultarClientes
     */
    public ConsultarClientes() {
        initComponents();
        cargarDatos();
    }
    
    public ConsultarClientes(Inicio inicioInstance) {
        initComponents();
        this.inicioInstance = inicioInstance;
        configurarListeners();
        
        // Cargar opciones del combo de filtrado si no están
        if (FiltradoCB.getItemCount() == 0 || FiltradoCB.getItemAt(0).equals("Item 1")) {
            FiltradoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-Z", "Más compras", "Más puntos" }));
        }
        
        cargarDatos();
    }
    
    private void configurarListeners() {
        // Listener Buscador
        BuscarTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cargarDatos(); 
            }
        });
        
        // Listener Combo Ordenar
        FiltradoCB.addActionListener(evt -> cargarDatos());
    }

    // 1. CARGAR DATOS DE LA BBDD
    private void cargarDatos() {
        String texto = BuscarTF.getText().trim();
        if(texto.equals("Buscar")) texto = ""; 
        
        int orden = FiltradoCB.getSelectedIndex(); 
        if (orden < 0) orden = 0;
        
        // Llamada al DAO
        listaCompleta = ClienteDAO.listarClientes(texto, orden);
        
        // Resetear a página 1 y pintar
        paginaActual = 1;
        pintarPagina();
    }

    // 2. PINTAR LA PÁGINA ACTUAL
    private void pintarPagina() {
        PanelMedio.removeAll();
        PanelMedio.setLayout(new javax.swing.BoxLayout(PanelMedio, javax.swing.BoxLayout.Y_AXIS));
        
        if (listaCompleta != null && !listaCompleta.isEmpty()) {
            int inicio = (paginaActual - 1) * ITEMS_POR_PAGINA;
            int fin = Math.min(inicio + ITEMS_POR_PAGINA, listaCompleta.size());
            
            for (int i = inicio; i < fin; i++) {
                Cliente c = listaCompleta.get(i);
                
                // Crear Item visual
                com.boquerontech.supermercadoboqueron.informes.items.ItemCliente item = 
                        new com.boquerontech.supermercadoboqueron.informes.items.ItemCliente();
                
                item.setDatos(c);
                PanelMedio.add(item);
                PanelMedio.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
            }
        } else {
            javax.swing.JLabel lblVacio = new javax.swing.JLabel("No se encontraron clientes.");
            PanelMedio.add(lblVacio);
        }
        
        // Actualizar el ComboBox de paginación para mostrar la página actual
        // Truco: lo usamos como visualizador
        NumPaginasCB.removeAllItems();
        NumPaginasCB.addItem(String.valueOf(paginaActual));
        
        PanelMedio.revalidate();
        PanelMedio.repaint();
    }
    
    // Botón Salir
    private void SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Volver a InicioDocumentos
        if (inicioInstance != null) {
            inicioInstance.colocarPanel(new InicioDocumentos(inicioInstance));
        }
    } 
    
    // Método placeholder para buscar (ya lo manejamos con listener, pero el botón lo llama)
    private void BuscarTFActionPerformed(java.awt.event.ActionEvent evt) {                                         
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelAbajo = new javax.swing.JPanel();
        SalirBtn = new javax.swing.JButton();
        NumPaginasCB = new javax.swing.JComboBox<>();
        PnlCentral = new javax.swing.JPanel();
        BuscarTF = new javax.swing.JTextField();
        FiltradoCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelMedio = new javax.swing.JPanel();
        pnlCabecera = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        relleno = new javax.swing.JPanel();
        trabajadorPanel = new javax.swing.JPanel();
        pnlUser = new javax.swing.JPanel();
        ListadoLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 253, 253));
        setLayout(new java.awt.BorderLayout());

        PanelAbajo.setOpaque(false);
        PanelAbajo.setLayout(new java.awt.GridBagLayout());

        SalirBtn.setForeground(new java.awt.Color(199, 108, 108));
        SalirBtn.setText("Salir");
        SalirBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 108, 108)));
        SalirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 0);
        PanelAbajo.add(SalirBtn, gridBagConstraints);

        NumPaginasCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        NumPaginasCB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 0);
        PanelAbajo.add(NumPaginasCB, gridBagConstraints);

        add(PanelAbajo, java.awt.BorderLayout.PAGE_END);

        PnlCentral.setOpaque(false);
        PnlCentral.setLayout(new java.awt.GridBagLayout());

        BuscarTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BuscarTF.setText("Buscar");
        BuscarTF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BuscarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 450, 0, 0);
        PnlCentral.add(BuscarTF, gridBagConstraints);

        FiltradoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-Z", "Más compras", "Más puntos" }));
        FiltradoCB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PnlCentral.add(FiltradoCB, gridBagConstraints);

        jScrollPane1.setViewportView(PanelMedio);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PnlCentral.add(jScrollPane1, gridBagConstraints);

        add(PnlCentral, java.awt.BorderLayout.CENTER);

        pnlCabecera.setBackground(new java.awt.Color(233, 253, 253));
        pnlCabecera.setLayout(new java.awt.GridBagLayout());

        lblTittle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(0, 0, 0));
        lblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle.setText("Consultar Clientes");
        lblTittle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        pnlCabecera.add(lblTittle, gridBagConstraints);

        relleno.setBackground(new java.awt.Color(204, 204, 204));
        relleno.setOpaque(false);
        relleno.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout rellenoLayout = new javax.swing.GroupLayout(relleno);
        relleno.setLayout(rellenoLayout);
        rellenoLayout.setHorizontalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        rellenoLayout.setVerticalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        pnlCabecera.add(relleno, gridBagConstraints);

        trabajadorPanel.setBackground(new java.awt.Color(204, 204, 204));
        trabajadorPanel.setPreferredSize(new java.awt.Dimension(200, 60));

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlUser.setPreferredSize(new java.awt.Dimension(161, 60));
        pnlUser.setLayout(new java.awt.GridBagLayout());

        ListadoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_torrente.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(ListadoLbl, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Torrente Segura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Jefe Boqueron");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel7, gridBagConstraints);

        javax.swing.GroupLayout trabajadorPanelLayout = new javax.swing.GroupLayout(trabajadorPanel);
        trabajadorPanel.setLayout(trabajadorPanelLayout);
        trabajadorPanelLayout.setHorizontalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trabajadorPanelLayout.setVerticalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        pnlCabecera.add(trabajadorPanel, gridBagConstraints);

        add(pnlCabecera, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JTextField BuscarTF;
    private javax.swing.JComboBox<String> FiltradoCB;
    private javax.swing.JLabel ListadoLbl;
    private javax.swing.JComboBox<String> NumPaginasCB;
    private javax.swing.JPanel PanelAbajo;
    private javax.swing.JPanel PanelMedio;
    private javax.swing.JPanel PnlCentral;
    private javax.swing.JButton SalirBtn;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JPanel relleno;
    private javax.swing.JPanel trabajadorPanel;
    // End of variables declaration                   
}