/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.informes;

import com.boquerontech.supermercadoboqueron.Inicio;

/**
 *
 * @author navas
 */
public class InicioDocumentos extends javax.swing.JPanel {

    private Inicio inicioInstance;
    /**
     * Creates new form InicioDocumentos
     */
    public InicioDocumentos() {
        initComponents();
    }
public InicioDocumentos(Inicio inicioInstance) {
        initComponents();
        this.inicioInstance = inicioInstance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlCentralBajo = new javax.swing.JPanel();
        BtnAnalisisyConsultas = new javax.swing.JButton();
        BtnGestionProductos = new javax.swing.JButton();
        BtnConsultasdeClientes = new javax.swing.JButton();
        pnlCabecera = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        relleno = new javax.swing.JPanel();
        trabajadorPanel = new javax.swing.JPanel();
        pnlUser = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 253, 253));
        setLayout(new java.awt.BorderLayout());

        PnlCentralBajo.setOpaque(false);
        PnlCentralBajo.setLayout(new java.awt.GridBagLayout());

        BtnAnalisisyConsultas.setBackground(new java.awt.Color(255, 255, 255));
        BtnAnalisisyConsultas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BtnAnalisisyConsultas.setForeground(new java.awt.Color(48, 91, 171));
        BtnAnalisisyConsultas.setText("Análisis y consultas");
        BtnAnalisisyConsultas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 91, 171)));
        BtnAnalisisyConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAnalisisyConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnalisisyConsultasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        PnlCentralBajo.add(BtnAnalisisyConsultas, gridBagConstraints);

        BtnGestionProductos.setBackground(new java.awt.Color(255, 255, 255));
        BtnGestionProductos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BtnGestionProductos.setForeground(new java.awt.Color(48, 91, 171));
        BtnGestionProductos.setText("Gestión de productos");
        BtnGestionProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 91, 171)));
        BtnGestionProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnGestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionProductosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 30, 0);
        PnlCentralBajo.add(BtnGestionProductos, gridBagConstraints);

        BtnConsultasdeClientes.setBackground(new java.awt.Color(255, 255, 255));
        BtnConsultasdeClientes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BtnConsultasdeClientes.setForeground(new java.awt.Color(48, 91, 171));
        BtnConsultasdeClientes.setText("Consultas de clientes");
        BtnConsultasdeClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 91, 171)));
        BtnConsultasdeClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnConsultasdeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultasdeClientesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        PnlCentralBajo.add(BtnConsultasdeClientes, gridBagConstraints);

        add(PnlCentralBajo, java.awt.BorderLayout.CENTER);

        pnlCabecera.setBackground(new java.awt.Color(233, 253, 253));
        pnlCabecera.setLayout(new java.awt.GridBagLayout());

        lblTittle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle.setText("Documentos");
        lblTittle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        pnlCabecera.add(lblTittle, gridBagConstraints);

        relleno.setBackground(new java.awt.Color(204, 204, 204));
        relleno.setOpaque(false);
        relleno.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout rellenoLayout = new javax.swing.GroupLayout(relleno);
        relleno.setLayout(rellenoLayout);
        rellenoLayout.setHorizontalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        rellenoLayout.setVerticalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        pnlCabecera.add(relleno, gridBagConstraints);

        trabajadorPanel.setBackground(new java.awt.Color(204, 204, 204));
        trabajadorPanel.setPreferredSize(new java.awt.Dimension(200, 60));

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlUser.setPreferredSize(new java.awt.Dimension(161, 60));
        pnlUser.setLayout(new java.awt.GridBagLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_torrente.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Torrente Segura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Jefe Boqueron");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel7, gridBagConstraints);

        javax.swing.GroupLayout trabajadorPanelLayout = new javax.swing.GroupLayout(trabajadorPanel);
        trabajadorPanel.setLayout(trabajadorPanelLayout);
        trabajadorPanelLayout.setHorizontalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trabajadorPanelLayout.setVerticalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        pnlCabecera.add(trabajadorPanel, gridBagConstraints);

        add(pnlCabecera, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAnalisisyConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnalisisyConsultasActionPerformed
        // TODO add your handling code here:
        
         inicioInstance.colocarPanel(new InicioAnalisisyConsultas(inicioInstance));
    }//GEN-LAST:event_BtnAnalisisyConsultasActionPerformed

    private void BtnGestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionProductosActionPerformed
        // TODO add your handling code here:
         inicioInstance.colocarPanel(new GestiondeProductos(inicioInstance));
    }//GEN-LAST:event_BtnGestionProductosActionPerformed

    private void BtnConsultasdeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultasdeClientesActionPerformed
        // TODO add your handling code here:
         inicioInstance.colocarPanel(new ConsultarClientes(inicioInstance));
    }//GEN-LAST:event_BtnConsultasdeClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnalisisyConsultas;
    private javax.swing.JButton BtnConsultasdeClientes;
    private javax.swing.JButton BtnGestionProductos;
    private javax.swing.JPanel PnlCentralBajo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JPanel relleno;
    private javax.swing.JPanel trabajadorPanel;
    // End of variables declaration//GEN-END:variables
}
