/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.informes;

import com.boquerontech.supermercadoboqueron.Inicio;
import com.boquerontech.supermercadoboqueron.promociones.InicioPromoP;
import javax.swing.JOptionPane;

/**
 *
 * @author navas
 */
public class Resumendecajadiaria extends javax.swing.JPanel {

    private Inicio inicioInstance;
    
    /**
     * Creates new form Resumendecajadiaria
     */
    public Resumendecajadiaria() {
        initComponents();
    }
public Resumendecajadiaria(Inicio inicioInstance) {
        initComponents();
        this.inicioInstance = inicioInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlBajo = new javax.swing.JPanel();
        SalirP2 = new javax.swing.JButton();
        GuardarP1 = new javax.swing.JButton();
        PnlCentral = new javax.swing.JPanel();
        LblIdEmpleado = new javax.swing.JLabel();
        TFIdEmpleado = new javax.swing.JTextField();
        LblFecha = new javax.swing.JLabel();
        TFFecha = new javax.swing.JTextField();
        LblValidacion = new javax.swing.JLabel();
        TFValidacion = new javax.swing.JTextField();
        LblIncidencia = new javax.swing.JLabel();
        TFIncidencia = new javax.swing.JTextField();
        pnlCabecera = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        relleno = new javax.swing.JPanel();
        trabajadorPanel = new javax.swing.JPanel();
        pnlUser = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 253, 253));
        setLayout(new java.awt.BorderLayout());

        PnlBajo.setOpaque(false);
        PnlBajo.setLayout(new java.awt.GridBagLayout());

        SalirP2.setForeground(new java.awt.Color(199, 108, 108));
        SalirP2.setText("Salir");
        SalirP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 108, 108)));
        SalirP2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SalirP2.setOpaque(true);
        SalirP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirP2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 39, 41, 0);
        PnlBajo.add(SalirP2, gridBagConstraints);

        GuardarP1.setForeground(new java.awt.Color(0, 121, 107));
        GuardarP1.setText("Guardar");
        GuardarP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 121, 107)));
        GuardarP1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GuardarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarP1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 646, 41, 26);
        PnlBajo.add(GuardarP1, gridBagConstraints);

        add(PnlBajo, java.awt.BorderLayout.PAGE_END);

        PnlCentral.setOpaque(false);
        PnlCentral.setLayout(new java.awt.GridBagLayout());

        LblIdEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblIdEmpleado.setText("ID-Empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        PnlCentral.add(LblIdEmpleado, gridBagConstraints);

        TFIdEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        TFIdEmpleado.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 2;
        PnlCentral.add(TFIdEmpleado, gridBagConstraints);

        LblFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblFecha.setText("Fecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        PnlCentral.add(LblFecha, gridBagConstraints);

        TFFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        TFFecha.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 2;
        PnlCentral.add(TFFecha, gridBagConstraints);

        LblValidacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblValidacion.setText("Validación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        PnlCentral.add(LblValidacion, gridBagConstraints);

        TFValidacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        TFValidacion.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 2;
        PnlCentral.add(TFValidacion, gridBagConstraints);

        LblIncidencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblIncidencia.setText("Incidencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        PnlCentral.add(LblIncidencia, gridBagConstraints);

        TFIncidencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        TFIncidencia.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 2;
        PnlCentral.add(TFIncidencia, gridBagConstraints);

        add(PnlCentral, java.awt.BorderLayout.CENTER);

        pnlCabecera.setBackground(new java.awt.Color(233, 253, 253));
        pnlCabecera.setLayout(new java.awt.GridBagLayout());

        lblTittle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle.setText("Resumen de Caja");
        lblTittle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        pnlCabecera.add(lblTittle, gridBagConstraints);

        relleno.setBackground(new java.awt.Color(204, 204, 204));
        relleno.setOpaque(false);
        relleno.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout rellenoLayout = new javax.swing.GroupLayout(relleno);
        relleno.setLayout(rellenoLayout);
        rellenoLayout.setHorizontalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        rellenoLayout.setVerticalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        pnlCabecera.add(relleno, gridBagConstraints);

        trabajadorPanel.setBackground(new java.awt.Color(204, 204, 204));
        trabajadorPanel.setPreferredSize(new java.awt.Dimension(200, 60));

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlUser.setPreferredSize(new java.awt.Dimension(161, 60));
        pnlUser.setLayout(new java.awt.GridBagLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_torrente.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Torrente Segura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Jefe Boqueron");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel9, gridBagConstraints);

        javax.swing.GroupLayout trabajadorPanelLayout = new javax.swing.GroupLayout(trabajadorPanel);
        trabajadorPanel.setLayout(trabajadorPanelLayout);
        trabajadorPanelLayout.setHorizontalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trabajadorPanelLayout.setVerticalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        pnlCabecera.add(trabajadorPanel, gridBagConstraints);

        add(pnlCabecera, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarP1ActionPerformed
        // TODO add your handling code here:
        // 1. RECOGER DATOS
        String idEmpStr = TFIdEmpleado.getText().trim();
        String fechaStr = TFFecha.getText().trim(); // Formato AAAA-MM-DD
        String validacion = TFValidacion.getText().trim();
        String incidencia = TFIncidencia.getText().trim();

        if (idEmpStr.isEmpty() || fechaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Empleado y Fecha son obligatorios.", "Faltan datos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. CONVERTIR TIPOS
            int idEmpleado = Integer.parseInt(idEmpStr);
            java.time.LocalDate fecha = java.time.LocalDate.parse(fechaStr);

            // 3. CREAR OBJETO
            com.boquerontech.supermercadoboqueron.informes.modelo.CierreCaja nuevoCierre = 
                new com.boquerontech.supermercadoboqueron.informes.modelo.CierreCaja(idEmpleado, fecha, validacion, incidencia);

            // 4. GUARDAR EN BD
            boolean exito = com.boquerontech.supermercadoboqueron.database.informes.CierreCajaDAO.insertarCierre(nuevoCierre);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Resumen guardado con éxito.\nListo para generar informe.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                // Volver atrás
                inicioInstance.colocarPanel(new InicioAnalisisyConsultas(inicioInstance));
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de empleado debe ser un número.", "Error formato", JOptionPane.WARNING_MESSAGE);
        } catch (java.time.format.DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto (use AAAA-MM-DD).", "Error fecha", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
        }
        JOptionPane.showMessageDialog(null, "Guardado con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_GuardarP1ActionPerformed

    private void SalirP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirP2ActionPerformed
        // TODO add your handling code here:
        inicioInstance.colocarPanel(new InicioAnalisisyConsultas(inicioInstance));
        if (inicioInstance != null) {
            inicioInstance.colocarPanel(new InicioAnalisisyConsultas(inicioInstance));
        }
    }//GEN-LAST:event_SalirP2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarP1;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel LblIdEmpleado;
    private javax.swing.JLabel LblIncidencia;
    private javax.swing.JLabel LblValidacion;
    private javax.swing.JPanel PnlBajo;
    private javax.swing.JPanel PnlCentral;
    private javax.swing.JButton SalirP2;
    private javax.swing.JTextField TFFecha;
    private javax.swing.JTextField TFIdEmpleado;
    private javax.swing.JTextField TFIncidencia;
    private javax.swing.JTextField TFValidacion;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JPanel relleno;
    private javax.swing.JPanel trabajadorPanel;
    // End of variables declaration//GEN-END:variables
}
