/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.inventario.items;

import com.boquerontech.supermercadoboqueron.inventario.Inventario;
import com.boquerontech.supermercadoboqueron.productos.Producto;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;

/**
 *
 * @author velag
 */
public class ProductoInventarioItem extends javax.swing.JPanel {    
    private JPopupMenu popup = new JPopupMenu();
    private Inventario inventario;
    
    private Producto producto;
    
    /**
     * Creates new form ProductoInventarioItem
     */
    public ProductoInventarioItem(Inventario inventario, Producto prod) {
        initComponents();
        
        this.inventario = inventario;
        
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    // Abrir el panel de configuración del producto
                    
                } else if (SwingUtilities.isRightMouseButton(e)) {
                    // Abrir el popup para acciones
                    showPopup(e);
                }
            }
            
        });
        
        producto = prod;
        
        nombreProducto.setText(prod.getNombre());
        stockProducto.setText(String.valueOf(prod.getStock()));
    }
    
    private void showPopup(MouseEvent e) {
        popup.removeAll();
        
        JMenuItem eliminarProd = new JMenuItem("Eliminar Producto");
        
        popup.add(eliminarProd).addActionListener(event -> eliminar());
        
        popup.show(e.getComponent(), e.getX(), e.getY());
    }
    
    private void eliminar() {
        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar el producto \"" + nombreProducto.getText() + "\"?\nEsta acción no se puede deshacer.",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE // Icono de advertencia para borrados
        );
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            // Método para eliminar el producto de la bbdd
            inventario.updateProductos(producto);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nombreProducto = new javax.swing.JLabel();
        stockProducto = new javax.swing.JLabel();
        iconProducto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 239, 239));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setLayout(new java.awt.GridBagLayout());

        nombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nombreProducto.setForeground(new java.awt.Color(0, 0, 0));
        nombreProducto.setText("{producto}");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 0);
        add(nombreProducto, gridBagConstraints);

        stockProducto.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        stockProducto.setForeground(new java.awt.Color(0, 0, 0));
        stockProducto.setText("{stock}");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 0);
        add(stockProducto, gridBagConstraints);

        iconProducto.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        add(iconProducto, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public void setIconProducto(String rutaIcono) {
        iconProducto.setIcon(new ImageIcon(getClass().getResource(rutaIcono)));
    }

    public String getNombreProducto() {
        return nombreProducto.getText().trim();
    }
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto.setText(nombreProducto);
    }

    public Integer getStockProducto() {
        return Integer.valueOf(stockProducto.getText().trim());
    }
    public void setStockProducto(Integer stockProducto) {
        this.stockProducto.setText(String.valueOf(stockProducto));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconProducto;
    private javax.swing.JLabel nombreProducto;
    private javax.swing.JLabel stockProducto;
    // End of variables declaration//GEN-END:variables
}
