/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.clientes;

/**
 *
 * @author adrih
 */
public class ConsultarCliente extends javax.swing.JPanel {

    /**
     * Creates new form NuevoCliente
     */
    public ConsultarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPnl = new javax.swing.JPanel();
        tituloLbl = new javax.swing.JLabel();
        nombreCompletoLbl = new javax.swing.JLabel();
        fechaNacimientoLbl = new javax.swing.JLabel();
        dniLbl = new javax.swing.JLabel();
        codClienteLbl = new javax.swing.JLabel();
        edadLbl = new javax.swing.JLabel();
        telefonoLbl = new javax.swing.JLabel();
        puntosLbl = new javax.swing.JLabel();
        nombreCompletoTxt = new javax.swing.JLabel();
        fechaNacimientoTxt = new javax.swing.JLabel();
        dniTxt = new javax.swing.JLabel();
        codigoClienteTxt = new javax.swing.JLabel();
        edadTxt = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JLabel();
        puntosTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchLblIcon = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        btnPnl = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(233, 253, 253));
        setLayout(new java.awt.BorderLayout());

        mainPnl.setBackground(new java.awt.Color(233, 253, 253));
        mainPnl.setLayout(new java.awt.GridBagLayout());

        tituloLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloLbl.setText("Consultar un cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        mainPnl.add(tituloLbl, gridBagConstraints);

        nombreCompletoLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nombreCompletoLbl.setText("Nombre y apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(nombreCompletoLbl, gridBagConstraints);

        fechaNacimientoLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        fechaNacimientoLbl.setText("Fecha de nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(fechaNacimientoLbl, gridBagConstraints);

        dniLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dniLbl.setText("DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(dniLbl, gridBagConstraints);

        codClienteLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        codClienteLbl.setText("Cod Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(codClienteLbl, gridBagConstraints);

        edadLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        edadLbl.setText("Edad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(edadLbl, gridBagConstraints);

        telefonoLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        telefonoLbl.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(telefonoLbl, gridBagConstraints);

        puntosLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        puntosLbl.setText("Puntos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(puntosLbl, gridBagConstraints);

        nombreCompletoTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nombreCompletoTxt.setText("<Nombre y apellidos>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(nombreCompletoTxt, gridBagConstraints);

        fechaNacimientoTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fechaNacimientoTxt.setText("<dd/mm/aaaa>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(fechaNacimientoTxt, gridBagConstraints);

        dniTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        dniTxt.setText("<12345678A>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(dniTxt, gridBagConstraints);

        codigoClienteTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        codigoClienteTxt.setText("<código cliente>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(codigoClienteTxt, gridBagConstraints);

        edadTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        edadTxt.setText("<Edad actual>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(edadTxt, gridBagConstraints);

        telefonoTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        telefonoTxt.setText("<+34 612345678>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(telefonoTxt, gridBagConstraints);

        puntosTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        puntosTxt.setText("<x ptos.>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        mainPnl.add(puntosTxt, gridBagConstraints);

        jScrollPane1.setBorder(null);

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Ptos./ud.", "Ptos. ganados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(220, 220, 220));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        mainPnl.add(jScrollPane1, gridBagConstraints);

        searchLblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_search.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mainPnl.add(searchLblIcon, gridBagConstraints);

        searchTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchTxt.setText("Buscador");
        searchTxt.setMargin(new java.awt.Insets(2, 25, 2, 6));
        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        mainPnl.add(searchTxt, gridBagConstraints);

        add(mainPnl, java.awt.BorderLayout.CENTER);

        btnPnl.setBackground(new java.awt.Color(233, 253, 253));
        btnPnl.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(117, 117, 117));
        jButton1.setText("Cerrar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(117, 117, 117), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 20, 20);
        btnPnl.add(jButton1, gridBagConstraints);

        add(btnPnl, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPnl;
    private javax.swing.JLabel codClienteLbl;
    private javax.swing.JLabel codigoClienteTxt;
    private javax.swing.JLabel dniLbl;
    private javax.swing.JLabel dniTxt;
    private javax.swing.JLabel edadLbl;
    private javax.swing.JLabel edadTxt;
    private javax.swing.JLabel fechaNacimientoLbl;
    private javax.swing.JLabel fechaNacimientoTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JLabel nombreCompletoLbl;
    private javax.swing.JLabel nombreCompletoTxt;
    private javax.swing.JLabel puntosLbl;
    private javax.swing.JLabel puntosTxt;
    private javax.swing.JLabel searchLblIcon;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JLabel telefonoLbl;
    private javax.swing.JLabel telefonoTxt;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
