/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.clientes;

import com.boquerontech.supermercadoboqueron.database.cliente.ClienteDAO;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author adrih
 */
public class ModificarCliente extends javax.swing.JPanel {

    private final ClienteDAO clienteDAO;
    private Cliente clienteActual;

    /**
     * Creates new form NuevoCliente
     */
    public ModificarCliente() {
        initComponents();
        clienteDAO = new ClienteDAO();
        clearFields();
        
        searchTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTxtMouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlCentral = new javax.swing.JPanel();
        tituloLbl = new javax.swing.JLabel();
        apellido1Lbl = new javax.swing.JLabel();
        apellido2Lbl = new javax.swing.JLabel();
        dniLbl = new javax.swing.JLabel();
        TelefLbl = new javax.swing.JLabel();
        fechaLbl = new javax.swing.JLabel();
        apellido1Txt = new javax.swing.JTextField();
        apellido2Txt = new javax.swing.JTextField();
        dniTxt = new javax.swing.JTextField();
        telefTxt = new javax.swing.JTextField();
        fechaTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        nombreLbl = new javax.swing.JLabel();
        prefijoCombo = new javax.swing.JComboBox<>();
        searchLblIcon = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        pnlBotones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(233, 253, 253));
        setLayout(new java.awt.BorderLayout());

        pnlCentral.setBackground(new java.awt.Color(233, 253, 253));
        pnlCentral.setLayout(new java.awt.GridBagLayout());

        tituloLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloLbl.setText("Modificar Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.insets = new java.awt.Insets(19, 0, 40, 0);
        pnlCentral.add(tituloLbl, gridBagConstraints);

        apellido1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apellido1Lbl.setText("Primer apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(apellido1Lbl, gridBagConstraints);

        apellido2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apellido2Lbl.setText("Segundo apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(apellido2Lbl, gridBagConstraints);

        dniLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dniLbl.setText("DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(dniLbl, gridBagConstraints);

        TelefLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TelefLbl.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(TelefLbl, gridBagConstraints);

        fechaLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechaLbl.setText("Fecha de nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(fechaLbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 238;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlCentral.add(apellido1Txt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 103;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlCentral.add(apellido2Txt, gridBagConstraints);

        dniTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(dniTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        pnlCentral.add(telefTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 103;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(fechaTxt, gridBagConstraints);

        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlCentral.add(nombreTxt, gridBagConstraints);

        nombreLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreLbl.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(nombreLbl, gridBagConstraints);

        prefijoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlCentral.add(prefijoCombo, gridBagConstraints);

        searchLblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_search.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlCentral.add(searchLblIcon, gridBagConstraints);

        searchTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchTxt.setText("Buscador");
        searchTxt.setMargin(new java.awt.Insets(2, 25, 2, 6));
        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlCentral.add(searchTxt, gridBagConstraints);

        add(pnlCentral, java.awt.BorderLayout.CENTER);

        pnlBotones.setBackground(new java.awt.Color(233, 253, 253));
        pnlBotones.setLayout(new java.awt.GridBagLayout());

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(117, 117, 117));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(117, 117, 117), 1, true));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 20, 20);
        pnlBotones.add(btnCancelar, gridBagConstraints);

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 121, 107));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 20, 20);
        pnlBotones.add(btnGuardar, gridBagConstraints);

        add(pnlBotones, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void dniTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTxtActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (clienteActual == null) {
            JOptionPane.showMessageDialog(this, "Primero busque y seleccione un cliente para modificar.", "Ningún cliente seleccionado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String nombre = nombreTxt.getText();
            String apellido1 = apellido1Txt.getText();
            String apellido2 = apellido2Txt.getText();
            String dni = dniTxt.getText();
            String telefono = telefTxt.getText();
            
            if (nombre.isEmpty() || apellido1.isEmpty() || dni.isEmpty() || telefono.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Los campos Nombre, Primer Apellido, DNI y Teléfono no pueden estar vacíos.", "Campos Requeridos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            clienteActual.setNombre(nombre);
            clienteActual.setApellidos(apellido1 + " " + apellido2);
            clienteActual.setDni(dni);
            clienteActual.setTelefono(telefono);

            if (!fechaTxt.getText().isEmpty()) {
                try {
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                    LocalDate fechaNacimiento = LocalDate.parse(fechaTxt.getText(), formatter);
                    clienteActual.setFechaNacimiento(fechaNacimiento);
                } catch (DateTimeParseException e) {
                    JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use YYYY-MM-DD.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            boolean exito = clienteDAO.actualizarCliente(clienteActual);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Cliente actualizado con éxito.", "Actualización Exitosa", JOptionPane.INFORMATION_MESSAGE);
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el cliente.", "Error de Actualización", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar el cliente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        String searchTerm = searchTxt.getText();
        if (searchTerm.isEmpty() || searchTerm.equals("Buscador")) {
            clearFields();
            return;
        }

        List<Cliente> clientes = clienteDAO.buscarClientesPorNombreOApellido(searchTerm);

        if (clientes.size() == 1) {
            clienteActual = clientes.get(0);
            populateFields(clienteActual);
        } else if (clientes.size() > 1) {
            clearFields();
            JOptionPane.showMessageDialog(this, "Se encontraron varios clientes con ese nombre. Por favor, sea más específico.", "Múltiples coincidencias", JOptionPane.WARNING_MESSAGE);
        } else {
            clearFields();
            JOptionPane.showMessageDialog(this, "No se encontró ningún cliente con ese nombre.", "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_searchTxtActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        clearFields();
    }
    
    private void searchTxtMouseClicked(java.awt.event.MouseEvent evt) {
        searchTxt.setText("");
    }
    
    private void populateFields(Cliente cliente) {
        nombreTxt.setText(cliente.getNombre());
        String[] apellidos = cliente.getApellidos().split(" ");
        apellido1Txt.setText(apellidos.length > 0 ? apellidos[0] : "");
        apellido2Txt.setText(apellidos.length > 1 ? apellidos[1] : "");
        dniTxt.setText(cliente.getDni());
        telefTxt.setText(cliente.getTelefono());
        if (cliente.getFechaNacimiento() != null) {
            fechaTxt.setText(cliente.getFechaNacimiento().toString());
        } else {
            fechaTxt.setText("");
        }
    }
    
    private void clearFields() {
        nombreTxt.setText("");
        apellido1Txt.setText("");
        apellido2Txt.setText("");
        dniTxt.setText("");
        telefTxt.setText("");
        fechaTxt.setText("");
        searchTxt.setText("Buscador");
        clienteActual = null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelefLbl;
    private javax.swing.JLabel apellido1Lbl;
    private javax.swing.JTextField apellido1Txt;
    private javax.swing.JLabel apellido2Lbl;
    private javax.swing.JTextField apellido2Txt;
    private javax.swing.JLabel dniLbl;
    private javax.swing.JTextField dniTxt;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JComboBox<String> prefijoCombo;
    private javax.swing.JLabel searchLblIcon;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTextField telefTxt;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}