/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.clientes;

import com.boquerontech.supermercadoboqueron.clientes.Cliente;
import com.boquerontech.supermercadoboqueron.database.cliente.ClienteDAO;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author adrih
 */
public class NuevoCliente extends javax.swing.JPanel {

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente() {
        initComponents();
        // Inicializar con valores vacíos o predeterminados si es necesario
        prefijoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+34", "+1", "+44", "+33" }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlCentral = new javax.swing.JPanel();
        tituloLbl = new javax.swing.JLabel();
        apellido1Lbl = new javax.swing.JLabel();
        apellido2Lbl = new javax.swing.JLabel();
        dniLbl = new javax.swing.JLabel();
        TelefLbl = new javax.swing.JLabel();
        fechaLbl = new javax.swing.JLabel();
        apellido1Txt = new javax.swing.JTextField();
        apellido2Txt = new javax.swing.JTextField();
        dniTxt = new javax.swing.JTextField();
        telefTxt = new javax.swing.JTextField();
        fechaTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        nombreLbl = new javax.swing.JLabel();
        prefijoCombo = new javax.swing.JComboBox<>();
        pnlBotones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(233, 253, 253));
        setLayout(new java.awt.BorderLayout());

        pnlCentral.setBackground(new java.awt.Color(233, 253, 253));
        pnlCentral.setLayout(new java.awt.GridBagLayout());

        tituloLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloLbl.setText("Dar de alta a un Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 107, 0, 0);
        pnlCentral.add(tituloLbl, gridBagConstraints);

        apellido1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apellido1Lbl.setText("Primer apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(apellido1Lbl, gridBagConstraints);

        apellido2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apellido2Lbl.setText("Segundo apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(apellido2Lbl, gridBagConstraints);

        dniLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dniLbl.setText("DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(dniLbl, gridBagConstraints);

        TelefLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TelefLbl.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(TelefLbl, gridBagConstraints);

        fechaLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechaLbl.setText("Fecha de nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(fechaLbl, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 238;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlCentral.add(apellido1Txt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 103;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlCentral.add(apellido2Txt, gridBagConstraints);

        dniTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(dniTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        pnlCentral.add(telefTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 103;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(fechaTxt, gridBagConstraints);

        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlCentral.add(nombreTxt, gridBagConstraints);

        nombreLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreLbl.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnlCentral.add(nombreLbl, gridBagConstraints);

        prefijoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlCentral.add(prefijoCombo, gridBagConstraints);

        add(pnlCentral, java.awt.BorderLayout.CENTER);

        pnlBotones.setBackground(new java.awt.Color(233, 253, 253));
        pnlBotones.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(117, 117, 117));
        jButton1.setText("Cancelar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(117, 117, 117), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 20, 20);
        pnlBotones.add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 121, 107));
        jButton2.setText("Guardar");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 20, 20);
        pnlBotones.add(jButton2, gridBagConstraints);

        add(pnlBotones, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void dniTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 1. Recoger los datos de los campos
        String nombre = nombreTxt.getText().trim();
        String apellido1 = apellido1Txt.getText().trim();
        String apellido2 = apellido2Txt.getText().trim();
        String dni = dniTxt.getText().trim();
        String prefijo = (String) prefijoCombo.getSelectedItem();
        String telefono = telefTxt.getText().trim();
        String fechaStr = fechaTxt.getText().trim();

        // 2. Validar que los campos obligatorios no estén vacíos
        if (nombre.isEmpty() || apellido1.isEmpty() || dni.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los campos Nombre, Primer Apellido, DNI y Teléfono son obligatorios.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Crear el objeto Cliente
        Cliente cliente = new Cliente();
        cliente.setNombre(nombre);
        cliente.setApellidos((apellido1 + " " + apellido2).trim());
        cliente.setDni(dni);
        cliente.setTelefono(prefijo + telefono);

        // 4. Procesar la fecha de nacimiento
        if (!fechaStr.isEmpty()) {
            try {
                // Asumimos formato AAAA-MM-DD
                LocalDate fechaNacimiento = LocalDate.parse(fechaStr);
                cliente.setFechaNacimiento(fechaNacimiento);
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(this, "El formato de la fecha de nacimiento no es válido. Use AAAA-MM-DD.", "Error de formato", JOptionPane.ERROR_MESSAGE);
                return; // Detener la ejecución si la fecha es inválida
            }
        }

        // 5. Usar el DAO para guardar el cliente
        ClienteDAO clienteDAO = new ClienteDAO();
        boolean exito = clienteDAO.crearCliente(cliente);

        // 6. Mostrar feedback al usuario
        if (exito) {
            JOptionPane.showMessageDialog(this, "Cliente guardado con éxito.", "Operación exitosa", JOptionPane.INFORMATION_MESSAGE);
            // 7. Limpiar los campos del formulario
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el cliente. Verifique los datos o consulte los logs.\nUn DNI o teléfono duplicado puede ser la causa.", "Error en la base de datos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void limpiarCampos() {
        nombreTxt.setText("");
        apellido1Txt.setText("");
        apellido2Txt.setText("");
        dniTxt.setText("");
        telefTxt.setText("");
        fechaTxt.setText("");
        prefijoCombo.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelefLbl;
    private javax.swing.JLabel apellido1Lbl;
    private javax.swing.JTextField apellido1Txt;
    private javax.swing.JLabel apellido2Lbl;
    private javax.swing.JTextField apellido2Txt;
    private javax.swing.JLabel dniLbl;
    private javax.swing.JTextField dniTxt;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JComboBox<String> prefijoCombo;
    private javax.swing.JTextField telefTxt;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
