/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.empleados;

import com.boquerontech.supermercadoboqueron.clientes.*;
import java.awt.CardLayout;

/**
 *
 * @author Adrian
 */
public class GestionEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form pnlInicio
     */
    public GestionEmpleado() {
        initComponents();
        pnlCard.add(new NuevoEmpleado(), "NuevoEmpleado");
        pnlCard.add(new ConsultarEmpleado(), "ConsultarEmpleado");
        pnlCard.add(new ModificarEmpleado(), "ModificarEmpleado");
        pnlCard.add(new EliminarEmpleado(), "EliminarEmpleado");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlHeader = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        pnlUser = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlFondo = new javax.swing.JPanel();
        pnlContenido = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pnlCard = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(233, 253, 253));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lblName.setBackground(new java.awt.Color(233, 253, 253));
        lblName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("EMPLEADOS");
        lblName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHeader.add(lblName, java.awt.BorderLayout.CENTER);

        pnlUser.setBackground(new java.awt.Color(233, 253, 253));
        pnlUser.setForeground(new java.awt.Color(0, 0, 0));
        pnlUser.setLayout(new java.awt.GridBagLayout());

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre Empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel6, gridBagConstraints);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Rol Empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel7, gridBagConstraints);

        pnlHeader.add(pnlUser, java.awt.BorderLayout.EAST);

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlFondo.setBackground(new java.awt.Color(233, 253, 253));
        pnlFondo.setLayout(new java.awt.BorderLayout());

        pnlContenido.setBackground(new java.awt.Color(233, 253, 253));
        pnlContenido.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnlContenido.setLayout(new java.awt.BorderLayout());

        pnlBotones.setBackground(new java.awt.Color(233, 253, 253));
        pnlBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnlBotones.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(100, 120, 200));
        jButton1.setText("NUEVO EMPLEADO");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 120, 200), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnlBotones.add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(100, 120, 200));
        jButton2.setText("CONSULTAR EMPLEADO");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 120, 200), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnlBotones.add(jButton2, gridBagConstraints);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(100, 120, 200));
        jButton3.setText("ELIMINAR EMPLEADO");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 120, 200), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnlBotones.add(jButton3, gridBagConstraints);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(100, 120, 200));
        jButton4.setText("MODIFICAR EMPLEADO");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 120, 200), 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnlBotones.add(jButton4, gridBagConstraints);

        pnlContenido.add(pnlBotones, java.awt.BorderLayout.WEST);

        pnlCard.setBackground(new java.awt.Color(233, 253, 253));
        pnlCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlCard.setLayout(new java.awt.CardLayout());
        pnlContenido.add(pnlCard, java.awt.BorderLayout.CENTER);

        pnlFondo.add(pnlContenido, java.awt.BorderLayout.CENTER);

        add(pnlFondo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cl = (CardLayout) pnlCard.getLayout();
        cl.show(pnlCard, "NuevoEmpleado");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout cl = (CardLayout) pnlCard.getLayout();
        cl.show(pnlCard, "ConsultarEmpleado");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CardLayout cl = (CardLayout) pnlCard.getLayout();
        cl.show(pnlCard, "ModificarEmpleado");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CardLayout cl = (CardLayout) pnlCard.getLayout();
        cl.show(pnlCard, "EliminarEmpleado");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlUser;
    // End of variables declaration//GEN-END:variables
}
