/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.promociones;

import com.boquerontech.supermercadoboqueron.Inicio;
import javax.swing.JOptionPane;

/**
 *
 * @author navas
 */
public class DaraltaPromoP extends javax.swing.JPanel {

    private Inicio inicioInstance;
    
    /**
     * Creates new form DaraltaPromoP
     */
    public DaraltaPromoP() {
        initComponents();
    }
    public DaraltaPromoP(Inicio inicioInstance) {
        initComponents();
        this.inicioInstance = inicioInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlBajo = new javax.swing.JPanel();
        CancelarP = new javax.swing.JButton();
        GuardarP1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LblNombre = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        LblTipo = new javax.swing.JLabel();
        TFTipo = new javax.swing.JTextField();
        LblAplicable = new javax.swing.JLabel();
        TFAplicable = new javax.swing.JTextField();
        LblReglas = new javax.swing.JLabel();
        TFReglas = new javax.swing.JTextField();
        LblVigencia = new javax.swing.JLabel();
        TFVigencia = new javax.swing.JTextField();
        LblProducto = new javax.swing.JLabel();
        TFProducto = new javax.swing.JTextField();
        CheckBConcurrente = new javax.swing.JCheckBox();
        LblImage = new javax.swing.JLabel();
        pnlCabecera = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        relleno = new javax.swing.JPanel();
        trabajadorPanel = new javax.swing.JPanel();
        pnlUser = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 253, 253));
        setLayout(new java.awt.BorderLayout());

        PnlBajo.setOpaque(false);
        PnlBajo.setLayout(new java.awt.GridBagLayout());

        CancelarP.setForeground(new java.awt.Color(199, 108, 108));
        CancelarP.setText("Cancelar");
        CancelarP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 108, 108)));
        CancelarP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CancelarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarPActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 350);
        PnlBajo.add(CancelarP, gridBagConstraints);

        GuardarP1.setForeground(new java.awt.Color(0, 121, 107));
        GuardarP1.setText("Guardar");
        GuardarP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 121, 107)));
        GuardarP1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GuardarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarP1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(20, 350, 20, 0);
        PnlBajo.add(GuardarP1, gridBagConstraints);

        add(PnlBajo, java.awt.BorderLayout.PAGE_END);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        LblNombre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblNombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel3.add(LblNombre, gridBagConstraints);

        TFNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel3.add(TFNombre, gridBagConstraints);

        LblTipo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblTipo.setText("Tipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel3.add(LblTipo, gridBagConstraints);

        TFTipo.setBackground(new java.awt.Color(255, 255, 255));
        TFTipo.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel3.add(TFTipo, gridBagConstraints);

        LblAplicable.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblAplicable.setText("Aplicable a:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel3.add(LblAplicable, gridBagConstraints);

        TFAplicable.setBackground(new java.awt.Color(255, 255, 255));
        TFAplicable.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel3.add(TFAplicable, gridBagConstraints);

        LblReglas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblReglas.setText("Reglas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel3.add(LblReglas, gridBagConstraints);

        TFReglas.setBackground(new java.awt.Color(255, 255, 255));
        TFReglas.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel3.add(TFReglas, gridBagConstraints);

        LblVigencia.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblVigencia.setText("Vigencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(LblVigencia, gridBagConstraints);

        TFVigencia.setBackground(new java.awt.Color(255, 255, 255));
        TFVigencia.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(TFVigencia, gridBagConstraints);

        LblProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LblProducto.setText("Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(LblProducto, gridBagConstraints);

        TFProducto.setBackground(new java.awt.Color(255, 255, 255));
        TFProducto.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(TFProducto, gridBagConstraints);

        CheckBConcurrente.setBackground(new java.awt.Color(233, 253, 253));
        CheckBConcurrente.setText("¿Es concurrente?");
        CheckBConcurrente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(CheckBConcurrente, gridBagConstraints);

        LblImage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LblImage.setText("IMAGE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel3.add(LblImage, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.CENTER);

        pnlCabecera.setBackground(new java.awt.Color(233, 253, 253));
        pnlCabecera.setLayout(new java.awt.GridBagLayout());

        lblTittle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle.setText("Dar Alta Promociones");
        lblTittle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        pnlCabecera.add(lblTittle, gridBagConstraints);

        relleno.setBackground(new java.awt.Color(204, 204, 204));
        relleno.setOpaque(false);
        relleno.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout rellenoLayout = new javax.swing.GroupLayout(relleno);
        relleno.setLayout(rellenoLayout);
        rellenoLayout.setHorizontalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        rellenoLayout.setVerticalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        pnlCabecera.add(relleno, gridBagConstraints);

        trabajadorPanel.setBackground(new java.awt.Color(204, 204, 204));
        trabajadorPanel.setPreferredSize(new java.awt.Dimension(200, 60));

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlUser.setPreferredSize(new java.awt.Dimension(161, 60));
        pnlUser.setLayout(new java.awt.GridBagLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_torrente.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Torrente Segura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Jefe Boqueron");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel12, gridBagConstraints);

        javax.swing.GroupLayout trabajadorPanelLayout = new javax.swing.GroupLayout(trabajadorPanel);
        trabajadorPanel.setLayout(trabajadorPanelLayout);
        trabajadorPanelLayout.setHorizontalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trabajadorPanelLayout.setVerticalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        pnlCabecera.add(trabajadorPanel, gridBagConstraints);

        add(pnlCabecera, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>                        

    private void CancelarPActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas cancelar?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if(opcion == JOptionPane.YES_OPTION){
            // Aquí lo que quieras hacer si el usuario pulsa "Sí"
            System.out.println("Cancelado.");
            inicioInstance.colocarPanel(new InicioPromoP(inicioInstance));
        } else {
            // Aquí lo que quieras si pulsa "No"
            System.out.println("No cancelado.");
        }
    }                                         

    private void GuardarP1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Guardado con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);
    }                                         


    // Variables declaration - do not modify                     
    private javax.swing.JButton CancelarP;
    private javax.swing.JCheckBox CheckBConcurrente;
    private javax.swing.JButton GuardarP1;
    private javax.swing.JLabel LblAplicable;
    private javax.swing.JLabel LblImage;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblProducto;
    private javax.swing.JLabel LblReglas;
    private javax.swing.JLabel LblTipo;
    private javax.swing.JLabel LblVigencia;
    private javax.swing.JPanel PnlBajo;
    private javax.swing.JTextField TFAplicable;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFProducto;
    private javax.swing.JTextField TFReglas;
    private javax.swing.JTextField TFTipo;
    private javax.swing.JTextField TFVigencia;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JPanel relleno;
    private javax.swing.JPanel trabajadorPanel;
    // End of variables declaration                   
}