/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.promociones;

import com.boquerontech.supermercadoboqueron.Inicio;
import com.boquerontech.supermercadoboqueron.database.DDBBConnector;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import com.boquerontech.supermercadoboqueron.promociones.Promocion; // Este es importante

/**
 *
 * @author navas
 */
public class ModificarPromocion extends javax.swing.JPanel {

    private Inicio inicioInstance;
    private com.boquerontech.supermercadoboqueron.promociones.Promocion promocionActual;

    /**
     * Constructor vacío (necesario a veces para el diseñador)
     */
    public ModificarPromocion() {
        initComponents();
    }

    /**
     * Constructor normal (para crear nueva, si se usara)
     */
    public ModificarPromocion(Inicio inicioInstance) {
        initComponents();
        this.inicioInstance = inicioInstance;
    }

    /**
     * CONSTRUCTOR PARA EDITAR (Recibe Inicio y la Promoción)
     */
    public ModificarPromocion(Inicio inicioInstance, com.boquerontech.supermercadoboqueron.promociones.Promocion promo) {
        initComponents();
        this.inicioInstance = inicioInstance;
        this.promocionActual = promo;
        
        cargarDatosEnFormulario(); // Rellenar campos al iniciar
    }

    // Método para poner los datos en los TextFields
    private void cargarDatosEnFormulario() {
        if (promocionActual != null) {
            nameTF.setText(promocionActual.getNombrePromocion());
            
            if (promocionActual.getFechaInicio() != null) {
                vigenciaTF.setText(promocionActual.getFechaInicio().toString());
            }
            
            tipoTF.setText(String.valueOf(promocionActual.getIdCategoria()));
            
            
        }
    }
    
    /**
     * Creates new form DaraltaPromoP
     */
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        midPanel = new javax.swing.JPanel();
        CancelarBtn = new javax.swing.JButton();
        GuardarBtn = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        tipoLbl = new javax.swing.JLabel();
        tipoTF = new javax.swing.JTextField();
        aplicableLbl = new javax.swing.JLabel();
        aplicableTF = new javax.swing.JTextField();
        reglasLbl = new javax.swing.JLabel();
        reglasTF = new javax.swing.JTextField();
        vigenciaLbl = new javax.swing.JLabel();
        vigenciaTF = new javax.swing.JTextField();
        productoLbl = new javax.swing.JLabel();
        productoTF = new javax.swing.JTextField();
        concurrenteCB = new javax.swing.JCheckBox();
        imagenLbl = new javax.swing.JLabel();
        pnlCabecera = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        relleno = new javax.swing.JPanel();
        trabajadorPanel = new javax.swing.JPanel();
        pnlUser = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 253, 253));
        setLayout(new java.awt.BorderLayout());

        midPanel.setOpaque(false);
        midPanel.setLayout(new java.awt.GridBagLayout());

        CancelarBtn.setBackground(new java.awt.Color(255, 255, 255));
        CancelarBtn.setForeground(new java.awt.Color(199, 108, 108));
        CancelarBtn.setText("Cancelar");
        CancelarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 108, 108)));
        CancelarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 350);
        midPanel.add(CancelarBtn, gridBagConstraints);

        GuardarBtn.setBackground(new java.awt.Color(255, 255, 255));
        GuardarBtn.setForeground(new java.awt.Color(0, 121, 107));
        GuardarBtn.setText("Guardar");
        GuardarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 121, 107)));
        GuardarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GuardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(20, 350, 20, 0);
        midPanel.add(GuardarBtn, gridBagConstraints);

        add(midPanel, java.awt.BorderLayout.PAGE_END);

        bottomPanel.setOpaque(false);
        bottomPanel.setLayout(new java.awt.GridBagLayout());

        nameLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(0, 0, 0));
        nameLbl.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        bottomPanel.add(nameLbl, gridBagConstraints);

        nameTF.setBackground(new java.awt.Color(255, 255, 255));
        nameTF.setForeground(new java.awt.Color(0, 0, 0));
        nameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        bottomPanel.add(nameTF, gridBagConstraints);

        tipoLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tipoLbl.setForeground(new java.awt.Color(0, 0, 0));
        tipoLbl.setText("Tipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        bottomPanel.add(tipoLbl, gridBagConstraints);

        tipoTF.setBackground(new java.awt.Color(255, 255, 255));
        tipoTF.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        bottomPanel.add(tipoTF, gridBagConstraints);

        aplicableLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        aplicableLbl.setForeground(new java.awt.Color(0, 0, 0));
        aplicableLbl.setText("Aplicable a:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        bottomPanel.add(aplicableLbl, gridBagConstraints);

        aplicableTF.setBackground(new java.awt.Color(255, 255, 255));
        aplicableTF.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        bottomPanel.add(aplicableTF, gridBagConstraints);

        reglasLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        reglasLbl.setForeground(new java.awt.Color(0, 0, 0));
        reglasLbl.setText("Reglas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        bottomPanel.add(reglasLbl, gridBagConstraints);

        reglasTF.setBackground(new java.awt.Color(255, 255, 255));
        reglasTF.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        bottomPanel.add(reglasTF, gridBagConstraints);

        vigenciaLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        vigenciaLbl.setForeground(new java.awt.Color(0, 0, 0));
        vigenciaLbl.setText("Vigencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        bottomPanel.add(vigenciaLbl, gridBagConstraints);

        vigenciaTF.setBackground(new java.awt.Color(255, 255, 255));
        vigenciaTF.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        bottomPanel.add(vigenciaTF, gridBagConstraints);

        productoLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        productoLbl.setForeground(new java.awt.Color(0, 0, 0));
        productoLbl.setText("Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        bottomPanel.add(productoLbl, gridBagConstraints);

        productoTF.setBackground(new java.awt.Color(255, 255, 255));
        productoTF.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        bottomPanel.add(productoTF, gridBagConstraints);

        concurrenteCB.setBackground(new java.awt.Color(233, 253, 253));
        concurrenteCB.setForeground(new java.awt.Color(0, 0, 0));
        concurrenteCB.setText("¿Es concurrente?");
        concurrenteCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        bottomPanel.add(concurrenteCB, gridBagConstraints);

        imagenLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imagenLbl.setForeground(new java.awt.Color(0, 0, 0));
        imagenLbl.setText("IMAGE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        bottomPanel.add(imagenLbl, gridBagConstraints);

        add(bottomPanel, java.awt.BorderLayout.CENTER);

        pnlCabecera.setBackground(new java.awt.Color(233, 253, 253));
        pnlCabecera.setLayout(new java.awt.GridBagLayout());

        lblTittle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle.setText("Promociones Concurrentes");
        lblTittle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        pnlCabecera.add(lblTittle, gridBagConstraints);

        relleno.setBackground(new java.awt.Color(204, 204, 204));
        relleno.setOpaque(false);
        relleno.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout rellenoLayout = new javax.swing.GroupLayout(relleno);
        relleno.setLayout(rellenoLayout);
        rellenoLayout.setHorizontalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        rellenoLayout.setVerticalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        pnlCabecera.add(relleno, gridBagConstraints);

        trabajadorPanel.setBackground(new java.awt.Color(204, 204, 204));
        trabajadorPanel.setPreferredSize(new java.awt.Dimension(200, 60));

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlUser.setPreferredSize(new java.awt.Dimension(161, 60));
        pnlUser.setLayout(new java.awt.GridBagLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_torrente.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Torrente Segura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Jefe Boqueron");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel12, gridBagConstraints);

        javax.swing.GroupLayout trabajadorPanelLayout = new javax.swing.GroupLayout(trabajadorPanel);
        trabajadorPanel.setLayout(trabajadorPanelLayout);
        trabajadorPanelLayout.setHorizontalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trabajadorPanelLayout.setVerticalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        pnlCabecera.add(trabajadorPanel, gridBagConstraints);

        add(pnlCabecera, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>                        

    private void CancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas cancelar?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if(opcion == JOptionPane.YES_OPTION){
            // Aquí lo que quieras hacer si el usuario pulsa "Sí"
            System.out.println("Cancelado.");
            inicioInstance.colocarPanel(new ModificarDardebajaPromocionP(inicioInstance));
        } else {
            // Aquí lo que quieras si pulsa "No"
            System.out.println("No cancelado.");
        }
        
    }                                           

    private void GuardarBtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // 1. Recoger datos modificados
        String nuevoNombre = nameTF.getText().trim();
        String nuevaVigencia = vigenciaTF.getText().trim();
        
        if (nuevoNombre.isEmpty() || nuevaVigencia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Faltan datos obligatorios.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Actualizar el objeto local
            promocionActual.setNombrePromocion(nuevoNombre);
            promocionActual.setFechaInicio(java.time.LocalDate.parse(nuevaVigencia));
            // Actualizar otros campos si los modificaste...
            
            // 2. LLAMAR AL DAO PARA ACTUALIZAR (UPDATE)
            boolean exito = com.boquerontech.supermercadoboqueron.database.promocion.PromocionDAO.actualizarPromocion(promocionActual);
            
            if (exito) {
                JOptionPane.showMessageDialog(null, "Modificación guardada con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);
                // Volver a la lista
                inicioInstance.colocarPanel(new ModificarDardebajaPromocionP(inicioInstance));
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar en BD.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en los datos: " + e.getMessage());
        }
    }      
    // Método para ACTUALIZAR una promoción existente
    public static boolean actualizarPromocion(Promocion promo) {
        String sql = "UPDATE Promociones SET nombrePromocion=?, unidadesAfectadas=?, precioPorUnidad=?, fechaInicio=?, fechaFin=?, Categoria_idCategoria=? WHERE idPromociones=?";
        
        try (Connection conn = DDBBConnector.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, promo.getNombrePromocion());
            pstmt.setInt(2, promo.getUnidadesAfectadas());
            pstmt.setDouble(3, promo.getPrecioPorUnidad());
            pstmt.setDate(4, Date.valueOf(promo.getFechaInicio()));
            
            if (promo.getFechaFin() != null) pstmt.setDate(5, Date.valueOf(promo.getFechaFin()));
            else pstmt.setDate(5, null);
            
            pstmt.setInt(6, promo.getIdCategoria());
            pstmt.setInt(7, promo.getIdPromociones()); // Importante: el ID para el WHERE

            return pstmt.executeUpdate() > 0;

        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton CancelarBtn;
    private javax.swing.JButton GuardarBtn;
    private javax.swing.JLabel aplicableLbl;
    private javax.swing.JTextField aplicableTF;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JCheckBox concurrenteCB;
    private javax.swing.JLabel imagenLbl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JPanel midPanel;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JLabel productoLbl;
    private javax.swing.JTextField productoTF;
    private javax.swing.JLabel reglasLbl;
    private javax.swing.JTextField reglasTF;
    private javax.swing.JPanel relleno;
    private javax.swing.JLabel tipoLbl;
    private javax.swing.JTextField tipoTF;
    private javax.swing.JPanel trabajadorPanel;
    private javax.swing.JLabel vigenciaLbl;
    private javax.swing.JTextField vigenciaTF;
    // End of variables declaration                   
}