/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.promociones;

import com.boquerontech.supermercadoboqueron.Inicio;
import javax.swing.JPanel;

/**
 *
 * @author navas
 */
public class ModificarDardebajaPromocionP extends javax.swing.JPanel {

    private Inicio inicioInstance;
    
    /**
     * Creates new form ModificarDardebajaPromocionP
     */
    public ModificarDardebajaPromocionP() {
        initComponents();
    }
    public ModificarDardebajaPromocionP(Inicio inicioInstance) {
        initComponents();
        this.inicioInstance = inicioInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topPanel = new javax.swing.JPanel();
        tituloLbl = new javax.swing.JLabel();
        usuarioLbl = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        salirBtn = new javax.swing.JButton();
        midPanel = new javax.swing.JPanel();
        buscarTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsPanel = new javax.swing.JPanel();
        itemModificardardebajaPromocion1 = new com.boquerontech.supermercadoboqueron.promociones.items.itemModificardardebajaPromocion();
        itemModificardardebajaPromocion2 = new com.boquerontech.supermercadoboqueron.promociones.items.itemModificardardebajaPromocion();

        setBackground(new java.awt.Color(233, 253, 253));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.BorderLayout());

        topPanel.setOpaque(false);
        topPanel.setLayout(new java.awt.GridBagLayout());

        tituloLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloLbl.setForeground(new java.awt.Color(0, 0, 0));
        tituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLbl.setText("Modificar/dar de baja promoción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 637;
        gridBagConstraints.ipady = 68;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        topPanel.add(tituloLbl, gridBagConstraints);

        usuarioLbl.setBackground(new java.awt.Color(255, 255, 255));
        usuarioLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usuarioLbl.setForeground(new java.awt.Color(0, 0, 0));
        usuarioLbl.setText("<html>Nombre empleado<br> <small>Rol empleado</small></html>");
        usuarioLbl.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 599, 0, 0);
        topPanel.add(usuarioLbl, gridBagConstraints);

        add(topPanel, java.awt.BorderLayout.PAGE_START);

        bottomPanel.setOpaque(false);
        bottomPanel.setLayout(new java.awt.GridBagLayout());

        salirBtn.setBackground(new java.awt.Color(255, 255, 255));
        salirBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salirBtn.setForeground(new java.awt.Color(199, 108, 108));
        salirBtn.setText("Salir");
        salirBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 108, 108)));
        salirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirBtn.setOpaque(true);
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 40, 0);
        bottomPanel.add(salirBtn, gridBagConstraints);

        add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        midPanel.setOpaque(false);
        midPanel.setLayout(new java.awt.GridBagLayout());

        buscarTF.setBackground(new java.awt.Color(233, 253, 253));
        buscarTF.setForeground(new java.awt.Color(0, 0, 0));
        buscarTF.setText("Buscar");
        buscarTF.setOpaque(true);
        buscarTF.setPreferredSize(new java.awt.Dimension(64, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        midPanel.add(buscarTF, gridBagConstraints);

        itemsPanel.add(itemModificardardebajaPromocion1);
        itemsPanel.add(itemModificardardebajaPromocion2);

        jScrollPane1.setViewportView(itemsPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 700;
        gridBagConstraints.ipady = 400;
        midPanel.add(jScrollPane1, gridBagConstraints);

        add(midPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        inicioInstance.colocarPanel(new InicioPromoP(inicioInstance));
        
    }//GEN-LAST:event_salirBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JTextField buscarTF;
    private com.boquerontech.supermercadoboqueron.promociones.items.itemModificardardebajaPromocion itemModificardardebajaPromocion1;
    private com.boquerontech.supermercadoboqueron.promociones.items.itemModificardardebajaPromocion itemModificardardebajaPromocion2;
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel midPanel;
    private javax.swing.JButton salirBtn;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel usuarioLbl;
    // End of variables declaration//GEN-END:variables
}
