/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.ventas;

/**
 *
 * @author velag
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        relleno = new javax.swing.JPanel();
        trabajadorPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigoProductoTxt = new javax.swing.JTextField();
        anadirProductoBtn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel4 = new javax.swing.JPanel();
        listaLbl = new javax.swing.JLabel();
        escaneadosScroll = new javax.swing.JScrollPane();
        usuarioLbl = new javax.swing.JLabel();
        usuarioPanel = new javax.swing.JPanel();
        clienteFoto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreClienteTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        prefijoTlfTxt = new javax.swing.JComboBox<>();
        enviarClienteBtn = new javax.swing.JButton();
        puntosLbl = new javax.swing.JLabel();
        metodoPagoLbl = new javax.swing.JLabel();
        metodoPagoPanel = new javax.swing.JPanel();
        ticketVirtualLbl = new javax.swing.JLabel();
        ticketVirtualPromocionesScroll = new javax.swing.JScrollPane();
        finalizarBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("VENTAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        relleno.setBackground(new java.awt.Color(204, 204, 204));
        relleno.setOpaque(false);
        relleno.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout rellenoLayout = new javax.swing.GroupLayout(relleno);
        relleno.setLayout(rellenoLayout);
        rellenoLayout.setHorizontalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        rellenoLayout.setVerticalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        jPanel2.add(relleno, gridBagConstraints);

        trabajadorPanel.setBackground(new java.awt.Color(204, 204, 204));
        trabajadorPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout trabajadorPanelLayout = new javax.swing.GroupLayout(trabajadorPanel);
        trabajadorPanel.setLayout(trabajadorPanelLayout);
        trabajadorPanelLayout.setHorizontalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        trabajadorPanelLayout.setVerticalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        jPanel2.add(trabajadorPanel, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setMaximumSize(new java.awt.Dimension(654165165, 40));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 40));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/codigoBarras.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        codigoProductoTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        codigoProductoTxt.setForeground(new java.awt.Color(150, 150, 150));
        codigoProductoTxt.setText("Código del producto");
        codigoProductoTxt.setMaximumSize(new java.awt.Dimension(300, 40));
        codigoProductoTxt.setMinimumSize(new java.awt.Dimension(300, 40));
        codigoProductoTxt.setPreferredSize(new java.awt.Dimension(300, 40));
        codigoProductoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoProductoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoProductoTxtFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel3.add(codigoProductoTxt, gridBagConstraints);

        anadirProductoBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        anadirProductoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proximo.png"))); // NOI18N
        anadirProductoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anadirProductoBtn.setMaximumSize(new java.awt.Dimension(40, 40));
        anadirProductoBtn.setMinimumSize(new java.awt.Dimension(40, 40));
        anadirProductoBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel3.add(anadirProductoBtn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(filler1, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        listaLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        listaLbl.setForeground(new java.awt.Color(0, 0, 0));
        listaLbl.setText("Lista de productos escaneados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 10, 10);
        jPanel4.add(listaLbl, gridBagConstraints);

        escaneadosScroll.setMinimumSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 10);
        jPanel4.add(escaneadosScroll, gridBagConstraints);

        usuarioLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usuarioLbl.setForeground(new java.awt.Color(0, 0, 0));
        usuarioLbl.setText("Ingresar Cliente (opcional)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 10, 10);
        jPanel4.add(usuarioLbl, gridBagConstraints);

        usuarioPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        usuarioPanel.setLayout(new java.awt.GridBagLayout());

        clienteFoto.setText("img");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        usuarioPanel.add(clienteFoto, gridBagConstraints);

        jLabel3.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        usuarioPanel.add(jLabel3, gridBagConstraints);

        nombreClienteTxt.setText("Nombre de cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        usuarioPanel.add(nombreClienteTxt, gridBagConstraints);

        jLabel4.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        usuarioPanel.add(jLabel4, gridBagConstraints);

        telefonoTxt.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        usuarioPanel.add(telefonoTxt, gridBagConstraints);

        prefijoTlfTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        usuarioPanel.add(prefijoTlfTxt, gridBagConstraints);

        enviarClienteBtn.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        usuarioPanel.add(enviarClienteBtn, gridBagConstraints);

        puntosLbl.setText("puntos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        usuarioPanel.add(puntosLbl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        jPanel4.add(usuarioPanel, gridBagConstraints);

        metodoPagoLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        metodoPagoLbl.setForeground(new java.awt.Color(0, 0, 0));
        metodoPagoLbl.setText("Método de pago");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(metodoPagoLbl, gridBagConstraints);

        metodoPagoPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        metodoPagoPanel.setMinimumSize(new java.awt.Dimension(0, 100));
        metodoPagoPanel.setPreferredSize(new java.awt.Dimension(188, 100));

        javax.swing.GroupLayout metodoPagoPanelLayout = new javax.swing.GroupLayout(metodoPagoPanel);
        metodoPagoPanel.setLayout(metodoPagoPanelLayout);
        metodoPagoPanelLayout.setHorizontalGroup(
            metodoPagoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        metodoPagoPanelLayout.setVerticalGroup(
            metodoPagoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 10);
        jPanel4.add(metodoPagoPanel, gridBagConstraints);

        ticketVirtualLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ticketVirtualLbl.setForeground(new java.awt.Color(0, 0, 0));
        ticketVirtualLbl.setText("Ticket virtual con promociones aplicadas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 10, 20);
        jPanel4.add(ticketVirtualLbl, gridBagConstraints);

        ticketVirtualPromocionesScroll.setMinimumSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 20);
        jPanel4.add(ticketVirtualPromocionesScroll, gridBagConstraints);

        finalizarBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finalizarBtn.setText("Finalizar Compra");
        finalizarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        finalizarBtn.setMaximumSize(new java.awt.Dimension(200, 40));
        finalizarBtn.setMinimumSize(new java.awt.Dimension(200, 40));
        finalizarBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 20);
        jPanel4.add(finalizarBtn, gridBagConstraints);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void codigoProductoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoProductoTxtFocusGained
        if (codigoProductoTxt.getText().equals("Código del producto")) {
            codigoProductoTxt.setText("");
            codigoProductoTxt.setForeground(new java.awt.Color(0, 0, 0)); // texto normal
        }
    }//GEN-LAST:event_codigoProductoTxtFocusGained

    private void codigoProductoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoProductoTxtFocusLost
        if (codigoProductoTxt.getText().trim().isEmpty()) {
        codigoProductoTxt.setText("Código del producto");
        codigoProductoTxt.setForeground(new java.awt.Color(150, 150, 150)); // texto placeholder gris
    }
    }//GEN-LAST:event_codigoProductoTxtFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirProductoBtn;
    private javax.swing.JLabel clienteFoto;
    private javax.swing.JTextField codigoProductoTxt;
    private javax.swing.JButton enviarClienteBtn;
    private javax.swing.JScrollPane escaneadosScroll;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton finalizarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel listaLbl;
    private javax.swing.JLabel metodoPagoLbl;
    private javax.swing.JPanel metodoPagoPanel;
    private javax.swing.JTextField nombreClienteTxt;
    private javax.swing.JComboBox<String> prefijoTlfTxt;
    private javax.swing.JLabel puntosLbl;
    private javax.swing.JPanel relleno;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JLabel ticketVirtualLbl;
    private javax.swing.JScrollPane ticketVirtualPromocionesScroll;
    private javax.swing.JPanel trabajadorPanel;
    private javax.swing.JLabel usuarioLbl;
    private javax.swing.JPanel usuarioPanel;
    // End of variables declaration//GEN-END:variables
}
