/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.ventas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JRadioButton;

/**
 *
 * @author velag
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        configurarEventosPago();
    }

    /*
    Método que sirve para cambiar el método seleccionado que aparece en el ticket virtual por el método
    seleccionado, este método evita tener que hacer 3 métodos separados (uno por cada opción de pago)
    */
    private void configurarEventosPago() {
        // Creamos el comportamiento común para los botones (la acción que realizará al cambiar el botón)
        ActionListener listenerPago = (ActionEvent evt) -> {
            // Obtenemos el botón que ha sido pulsado
            JRadioButton botonSeleccionado = (JRadioButton) evt.getSource();
            
            // Actualizamos el label con el texto del botón (Ej: "Efectivo", "Bizum", etc.)
            metodoPagoLabel.setText("Método de pago: " + botonSeleccionado.getText());
        };

        // Asignamos este comportamiento a tus tres botones
        efectivoOpt.addActionListener(listenerPago);
        tarjetaOpt.addActionListener(listenerPago);
        bizumOpt.addActionListener(listenerPago);

        // Como el método seleccionado por defecto es Efectivo, se pone éste por defecto en el ticket virutal
        if (efectivoOpt.isSelected()) {
            metodoPagoLabel.setText("Método de pago: " + efectivoOpt.getText());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        metodosDePagoGroup = new javax.swing.ButtonGroup();
        cabecera = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        relleno = new javax.swing.JPanel();
        trabajadorPanel = new javax.swing.JPanel();
        pnlUser = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        panelCodigoProd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigoProductoTxt = new javax.swing.JTextField();
        anadirProductoBtn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        mainPanel = new javax.swing.JPanel();
        listaLbl = new javax.swing.JLabel();
        usuarioLbl = new javax.swing.JLabel();
        usuarioPanel = new javax.swing.JPanel();
        clienteFoto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreClienteTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        enviarClienteBtn = new javax.swing.JButton();
        puntosLbl = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        metodoPagoLbl = new javax.swing.JLabel();
        metodoPagoPanel = new javax.swing.JPanel();
        efectivoOpt = new javax.swing.JRadioButton();
        tarjetaOpt = new javax.swing.JRadioButton();
        bizumOpt = new javax.swing.JRadioButton();
        ticketVirtualLbl = new javax.swing.JLabel();
        finalizarBtn = new javax.swing.JButton();
        escaneadosPanel = new javax.swing.JPanel();
        bottomEscaneados = new javax.swing.JPanel();
        totalEscaneadosLabel = new javax.swing.JLabel();
        escaneadosScroll = new javax.swing.JScrollPane();
        escaneadosPanelRellenar = new javax.swing.JPanel();
        productoEscaneadoItem1 = new com.boquerontech.supermercadoboqueron.ventas.items.ProductoEscaneadoItem();
        ticketVirtualPanel = new javax.swing.JPanel();
        bottomTickVirt = new javax.swing.JPanel();
        totalTicketVirtualLabel = new javax.swing.JLabel();
        atendidoLabel = new javax.swing.JLabel();
        metodoPagoLabel = new javax.swing.JLabel();
        TickVirtScroll = new javax.swing.JScrollPane();
        ticketVirtualPanelRellenar = new javax.swing.JPanel();
        productoEscaneadoItem2 = new com.boquerontech.supermercadoboqueron.ventas.items.ProductoEscaneadoItem();

        setBackground(new java.awt.Color(233, 253, 253));
        setLayout(new java.awt.BorderLayout());

        cabecera.setOpaque(false);
        cabecera.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VENTAS");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        cabecera.add(jLabel2, gridBagConstraints);

        relleno.setBackground(new java.awt.Color(204, 204, 204));
        relleno.setOpaque(false);
        relleno.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout rellenoLayout = new javax.swing.GroupLayout(relleno);
        relleno.setLayout(rellenoLayout);
        rellenoLayout.setHorizontalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        rellenoLayout.setVerticalGroup(
            rellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        cabecera.add(relleno, gridBagConstraints);

        trabajadorPanel.setBackground(new java.awt.Color(204, 204, 204));
        trabajadorPanel.setPreferredSize(new java.awt.Dimension(200, 60));

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlUser.setPreferredSize(new java.awt.Dimension(161, 60));
        pnlUser.setLayout(new java.awt.GridBagLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_torrente.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Torrente Segura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Jefe Boqueron");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        pnlUser.add(jLabel7, gridBagConstraints);

        javax.swing.GroupLayout trabajadorPanelLayout = new javax.swing.GroupLayout(trabajadorPanel);
        trabajadorPanel.setLayout(trabajadorPanelLayout);
        trabajadorPanelLayout.setHorizontalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trabajadorPanelLayout.setVerticalGroup(
            trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(trabajadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        cabecera.add(trabajadorPanel, gridBagConstraints);

        add(cabecera, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setOpaque(false);
        bodyPanel.setLayout(new java.awt.BorderLayout());

        panelCodigoProd.setMaximumSize(new java.awt.Dimension(654165165, 40));
        panelCodigoProd.setMinimumSize(new java.awt.Dimension(400, 40));
        panelCodigoProd.setOpaque(false);
        panelCodigoProd.setPreferredSize(new java.awt.Dimension(400, 40));
        panelCodigoProd.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/codigoBarras.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        panelCodigoProd.add(jLabel1, gridBagConstraints);

        codigoProductoTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        codigoProductoTxt.setForeground(new java.awt.Color(150, 150, 150));
        codigoProductoTxt.setText("Código del producto");
        codigoProductoTxt.setMaximumSize(new java.awt.Dimension(300, 40));
        codigoProductoTxt.setMinimumSize(new java.awt.Dimension(300, 40));
        codigoProductoTxt.setPreferredSize(new java.awt.Dimension(300, 40));
        codigoProductoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoProductoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoProductoTxtFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelCodigoProd.add(codigoProductoTxt, gridBagConstraints);

        anadirProductoBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        anadirProductoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proximo.png"))); // NOI18N
        anadirProductoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anadirProductoBtn.setMaximumSize(new java.awt.Dimension(40, 40));
        anadirProductoBtn.setMinimumSize(new java.awt.Dimension(40, 40));
        anadirProductoBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelCodigoProd.add(anadirProductoBtn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelCodigoProd.add(filler1, gridBagConstraints);

        bodyPanel.add(panelCodigoProd, java.awt.BorderLayout.PAGE_START);

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.GridBagLayout());

        listaLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        listaLbl.setText("Lista de productos escaneados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 10, 10);
        mainPanel.add(listaLbl, gridBagConstraints);

        usuarioLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usuarioLbl.setText("Ingresar Cliente (opcional)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 10, 10);
        mainPanel.add(usuarioLbl, gridBagConstraints);

        usuarioPanel.setBackground(new java.awt.Color(255, 255, 255));
        usuarioPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        usuarioPanel.setMaximumSize(new java.awt.Dimension(300, 200));
        usuarioPanel.setMinimumSize(new java.awt.Dimension(300, 200));
        usuarioPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        usuarioPanel.setLayout(new java.awt.GridBagLayout());

        clienteFoto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clienteFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_user.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        usuarioPanel.add(clienteFoto, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        usuarioPanel.add(jLabel3, gridBagConstraints);

        nombreClienteTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreClienteTxt.setForeground(new java.awt.Color(150, 150, 150));
        nombreClienteTxt.setText("Nombre de cliente");
        nombreClienteTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreClienteTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreClienteTxtFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        usuarioPanel.add(nombreClienteTxt, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        usuarioPanel.add(jLabel4, gridBagConstraints);

        telefonoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefonoTxt.setForeground(new java.awt.Color(150, 150, 150));
        telefonoTxt.setText("612345678");
        telefonoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoTxtFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        usuarioPanel.add(telefonoTxt, gridBagConstraints);

        enviarClienteBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enviarClienteBtn.setText("LogIn");
        enviarClienteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        usuarioPanel.add(enviarClienteBtn, gridBagConstraints);

        puntosLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        puntosLbl.setText("{puntos}");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        usuarioPanel.add(puntosLbl, gridBagConstraints);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("+"))));
        jFormattedTextField1.setText("+34");
        jFormattedTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        usuarioPanel.add(jFormattedTextField1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        mainPanel.add(usuarioPanel, gridBagConstraints);

        metodoPagoLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        metodoPagoLbl.setText("Método de pago");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        mainPanel.add(metodoPagoLbl, gridBagConstraints);

        metodoPagoPanel.setBackground(new java.awt.Color(255, 255, 255));
        metodoPagoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        metodoPagoPanel.setMaximumSize(new java.awt.Dimension(300, 200));
        metodoPagoPanel.setMinimumSize(new java.awt.Dimension(300, 200));
        metodoPagoPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        metodoPagoPanel.setLayout(new java.awt.GridBagLayout());

        metodosDePagoGroup.add(efectivoOpt);
        efectivoOpt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        efectivoOpt.setSelected(true);
        efectivoOpt.setText("Efectivo");
        efectivoOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        metodoPagoPanel.add(efectivoOpt, gridBagConstraints);

        metodosDePagoGroup.add(tarjetaOpt);
        tarjetaOpt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tarjetaOpt.setText("Tarjeta de Crédito");
        tarjetaOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        metodoPagoPanel.add(tarjetaOpt, gridBagConstraints);

        metodosDePagoGroup.add(bizumOpt);
        bizumOpt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bizumOpt.setText("Bizum");
        bizumOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        metodoPagoPanel.add(bizumOpt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 10);
        mainPanel.add(metodoPagoPanel, gridBagConstraints);

        ticketVirtualLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ticketVirtualLbl.setText("Ticket virtual con promociones aplicadas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 10, 20);
        mainPanel.add(ticketVirtualLbl, gridBagConstraints);

        finalizarBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finalizarBtn.setText("Finalizar Compra");
        finalizarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        finalizarBtn.setMaximumSize(new java.awt.Dimension(200, 40));
        finalizarBtn.setMinimumSize(new java.awt.Dimension(200, 40));
        finalizarBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 20);
        mainPanel.add(finalizarBtn, gridBagConstraints);

        escaneadosPanel.setBackground(new java.awt.Color(255, 255, 255));
        escaneadosPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        escaneadosPanel.setPreferredSize(new java.awt.Dimension(598, 683));
        escaneadosPanel.setLayout(new java.awt.BorderLayout());

        bottomEscaneados.setOpaque(false);
        bottomEscaneados.setPreferredSize(new java.awt.Dimension(526, 100));
        bottomEscaneados.setLayout(new java.awt.GridBagLayout());

        totalEscaneadosLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        totalEscaneadosLabel.setText("Total de la compra = {total}");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        bottomEscaneados.add(totalEscaneadosLabel, gridBagConstraints);

        escaneadosPanel.add(bottomEscaneados, java.awt.BorderLayout.PAGE_END);

        escaneadosScroll.setBackground(new java.awt.Color(255, 51, 51));
        escaneadosScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        escaneadosScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        escaneadosScroll.setOpaque(false);

        escaneadosPanelRellenar.setBackground(new java.awt.Color(255, 255, 255));
        escaneadosPanelRellenar.setLayout(new javax.swing.BoxLayout(escaneadosPanelRellenar, javax.swing.BoxLayout.Y_AXIS));
        escaneadosPanelRellenar.add(productoEscaneadoItem1);

        escaneadosScroll.setViewportView(escaneadosPanelRellenar);

        escaneadosPanel.add(escaneadosScroll, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 10);
        mainPanel.add(escaneadosPanel, gridBagConstraints);

        ticketVirtualPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ticketVirtualPanel.setLayout(new java.awt.BorderLayout());

        bottomTickVirt.setBackground(new java.awt.Color(255, 255, 255));
        bottomTickVirt.setPreferredSize(new java.awt.Dimension(526, 100));
        bottomTickVirt.setLayout(new java.awt.GridBagLayout());

        totalTicketVirtualLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        totalTicketVirtualLabel.setText("Total de la compra = {total}");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 5, 20);
        bottomTickVirt.add(totalTicketVirtualLabel, gridBagConstraints);

        atendidoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        atendidoLabel.setText("Atendido por: {emp}");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 20, 10);
        bottomTickVirt.add(atendidoLabel, gridBagConstraints);

        metodoPagoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        metodoPagoLabel.setText("Método de pago: {met}");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 20, 20);
        bottomTickVirt.add(metodoPagoLabel, gridBagConstraints);

        ticketVirtualPanel.add(bottomTickVirt, java.awt.BorderLayout.PAGE_END);

        TickVirtScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        TickVirtScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ticketVirtualPanelRellenar.setPreferredSize(new java.awt.Dimension(526, 581));
        ticketVirtualPanelRellenar.setLayout(new javax.swing.BoxLayout(ticketVirtualPanelRellenar, javax.swing.BoxLayout.Y_AXIS));

        productoEscaneadoItem2.setBackground(new java.awt.Color(255, 255, 255));
        productoEscaneadoItem2.setOpaque(true);
        ticketVirtualPanelRellenar.add(productoEscaneadoItem2);

        TickVirtScroll.setViewportView(ticketVirtualPanelRellenar);

        ticketVirtualPanel.add(TickVirtScroll, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 20);
        mainPanel.add(ticketVirtualPanel, gridBagConstraints);

        bodyPanel.add(mainPanel, java.awt.BorderLayout.CENTER);

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    private void codigoProductoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoProductoTxtFocusGained
        if (codigoProductoTxt.getText().equals("Código del producto")) {
            codigoProductoTxt.setText("");
            codigoProductoTxt.setForeground(new java.awt.Color(0, 0, 0)); // texto normal
        }
    }//GEN-LAST:event_codigoProductoTxtFocusGained

    private void codigoProductoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoProductoTxtFocusLost
        if (codigoProductoTxt.getText().trim().isEmpty()) {
            codigoProductoTxt.setText("Código del producto");
            codigoProductoTxt.setForeground(new java.awt.Color(150, 150, 150)); // texto placeholder gris
        }
    }//GEN-LAST:event_codigoProductoTxtFocusLost

    private void nombreClienteTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreClienteTxtFocusGained
        if (nombreClienteTxt.getText().equals("Nombre de cliente")) {
            nombreClienteTxt.setText("");
            nombreClienteTxt.setForeground(new java.awt.Color(0, 0, 0)); // texto normal
        }
    }//GEN-LAST:event_nombreClienteTxtFocusGained

    private void nombreClienteTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreClienteTxtFocusLost
        if (nombreClienteTxt.getText().trim().isEmpty()) {
            nombreClienteTxt.setText("Nombre de cliente");
            nombreClienteTxt.setForeground(new java.awt.Color(150, 150, 150)); // texto placeholder gris
        }
    }//GEN-LAST:event_nombreClienteTxtFocusLost

    private void telefonoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoTxtFocusGained
        if (telefonoTxt.getText().equals("612345678")) {
            telefonoTxt.setText("");
            telefonoTxt.setForeground(new java.awt.Color(0, 0, 0)); // texto normal
        }
    }//GEN-LAST:event_telefonoTxtFocusGained

    private void telefonoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoTxtFocusLost
        if (telefonoTxt.getText().trim().isEmpty()) {
            telefonoTxt.setText("612345678");
            telefonoTxt.setForeground(new java.awt.Color(150, 150, 150)); // texto placeholder gris
        }
    }//GEN-LAST:event_telefonoTxtFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TickVirtScroll;
    private javax.swing.JButton anadirProductoBtn;
    private javax.swing.JLabel atendidoLabel;
    private javax.swing.JRadioButton bizumOpt;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel bottomEscaneados;
    private javax.swing.JPanel bottomTickVirt;
    private javax.swing.JPanel cabecera;
    private javax.swing.JLabel clienteFoto;
    private javax.swing.JTextField codigoProductoTxt;
    private javax.swing.JRadioButton efectivoOpt;
    private javax.swing.JButton enviarClienteBtn;
    private javax.swing.JPanel escaneadosPanel;
    private javax.swing.JPanel escaneadosPanelRellenar;
    private javax.swing.JScrollPane escaneadosScroll;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton finalizarBtn;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel listaLbl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel metodoPagoLabel;
    private javax.swing.JLabel metodoPagoLbl;
    private javax.swing.JPanel metodoPagoPanel;
    private javax.swing.ButtonGroup metodosDePagoGroup;
    private javax.swing.JTextField nombreClienteTxt;
    private javax.swing.JPanel panelCodigoProd;
    private javax.swing.JPanel pnlUser;
    private com.boquerontech.supermercadoboqueron.ventas.items.ProductoEscaneadoItem productoEscaneadoItem1;
    private com.boquerontech.supermercadoboqueron.ventas.items.ProductoEscaneadoItem productoEscaneadoItem2;
    private javax.swing.JLabel puntosLbl;
    private javax.swing.JPanel relleno;
    private javax.swing.JRadioButton tarjetaOpt;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JLabel ticketVirtualLbl;
    private javax.swing.JPanel ticketVirtualPanel;
    private javax.swing.JPanel ticketVirtualPanelRellenar;
    private javax.swing.JLabel totalEscaneadosLabel;
    private javax.swing.JLabel totalTicketVirtualLabel;
    private javax.swing.JPanel trabajadorPanel;
    private javax.swing.JLabel usuarioLbl;
    private javax.swing.JPanel usuarioPanel;
    // End of variables declaration//GEN-END:variables
}
