/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.productos;

import com.boquerontech.supermercadoboqueron.database.producto.ProductoDAO;
import com.boquerontech.supermercadoboqueron.inventario.Inventario;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author velag
 */
public class ProductoInfoDialog extends javax.swing.JDialog {
    private boolean modificacion = false;
    private Inventario inventario;
    private Producto producto;
    
    public ProductoInfoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public ProductoInfoDialog(java.awt.Frame parent, boolean modal, Producto producto, List<Categoria> categorias, Inventario inventario) {
        super(parent, modal);
        initComponents();
        this.inventario = inventario;
        this.producto = producto;
        this.setTitle("Información de " + producto.getNombre());
        
        setLocationRelativeTo(parent);
        
        // 1. Rellenar combo
        for (Categoria cat : categorias) categoriasCombo.addItem(cat.getNombre());
        
        // 2. Ocultar combo inicialmente
        categoriasCombo.setVisible(false);
        
        setDialogTitle(producto);
        setProductData(producto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        tituloDialog = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        modificarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        productId = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        productPrice = new javax.swing.JTextField();
        currentStock = new javax.swing.JTextField();
        minStock = new javax.swing.JTextField();
        productoCategory = new javax.swing.JTextField();
        productImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        acceptBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        categoriasCombo = new javax.swing.JComboBox<>();
        enableProduct = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(233, 253, 253));
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(233, 253, 253));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        tituloDialog.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloDialog.setForeground(new java.awt.Color(0, 0, 0));
        tituloDialog.setText("Información de {nombre}");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        jPanel1.add(tituloDialog, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(233, 253, 253));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        modificarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modificarBtn.setText("Modificar Producto");
        modificarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarBtn.setMaximumSize(new java.awt.Dimension(160, 27));
        modificarBtn.setMinimumSize(new java.awt.Dimension(160, 27));
        modificarBtn.setPreferredSize(new java.awt.Dimension(160, 27));
        modificarBtn.addActionListener(this::habilitarModificacion);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 5, 30);
        jPanel2.add(modificarBtn, gridBagConstraints);

        eliminarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eliminarBtn.setText("Eliminar Producto");
        eliminarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarBtn.setMaximumSize(new java.awt.Dimension(160, 27));
        eliminarBtn.setMinimumSize(new java.awt.Dimension(160, 27));
        eliminarBtn.setPreferredSize(new java.awt.Dimension(160, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 30);
        jPanel2.add(eliminarBtn, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_biometric.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 5, 10);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_name.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 5, 10);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_money.png"))); // NOI18N
        jLabel4.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 5, 10);
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_chart_up.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_chart_down.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_categoria.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(jLabel7, gridBagConstraints);

        productId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productId.setText("id");
        productId.setEnabled(false);
        productId.setMaximumSize(new java.awt.Dimension(150, 26));
        productId.setMinimumSize(new java.awt.Dimension(150, 26));
        productId.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(productId, gridBagConstraints);

        productName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productName.setText("nombre");
        productName.setEnabled(false);
        productName.setMaximumSize(new java.awt.Dimension(150, 26));
        productName.setMinimumSize(new java.awt.Dimension(150, 26));
        productName.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(productName, gridBagConstraints);

        productPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productPrice.setText("precio");
        productPrice.setEnabled(false);
        productPrice.setMaximumSize(new java.awt.Dimension(150, 26));
        productPrice.setMinimumSize(new java.awt.Dimension(150, 26));
        productPrice.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel2.add(productPrice, gridBagConstraints);

        currentStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        currentStock.setText("stock");
        currentStock.setEnabled(false);
        currentStock.setMaximumSize(new java.awt.Dimension(150, 26));
        currentStock.setMinimumSize(new java.awt.Dimension(150, 26));
        currentStock.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 30);
        jPanel2.add(currentStock, gridBagConstraints);

        minStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        minStock.setText("minStock");
        minStock.setEnabled(false);
        minStock.setMaximumSize(new java.awt.Dimension(150, 26));
        minStock.setMinimumSize(new java.awt.Dimension(150, 26));
        minStock.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 30);
        jPanel2.add(minStock, gridBagConstraints);

        productoCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productoCategory.setText("categoria");
        productoCategory.setEnabled(false);
        productoCategory.setMaximumSize(new java.awt.Dimension(150, 26));
        productoCategory.setMinimumSize(new java.awt.Dimension(150, 26));
        productoCategory.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 30);
        jPanel2.add(productoCategory, gridBagConstraints);

        productImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_vacio.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 5, 10);
        jPanel2.add(productImage, gridBagConstraints);

        jPanel3.setEnabled(false);
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        acceptBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acceptBtn.setText("Confirmar");
        acceptBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acceptBtn.addActionListener(this::confirmarAciton);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(acceptBtn, gridBagConstraints);

        cancelBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelBtn.setText("Cancelar");
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addActionListener(this::cancelAction);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(cancelBtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 15, 30);
        jPanel2.add(jPanel3, gridBagConstraints);

        categoriasCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoriasCombo.setMaximumRowCount(5);
        categoriasCombo.setMaximumSize(new java.awt.Dimension(150, 26));
        categoriasCombo.setMinimumSize(new java.awt.Dimension(150, 26));
        categoriasCombo.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 30);
        jPanel2.add(categoriasCombo, gridBagConstraints);

        enableProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enableProduct.setForeground(new java.awt.Color(0, 0, 0));
        enableProduct.setText("Producto Habilitado");
        enableProduct.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 30, 30);
        jPanel2.add(enableProduct, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void habilitarModificacion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habilitarModificacion
        modificacion = true;
        productName.setEnabled(true);
        productPrice.setEnabled(true);
        minStock.setEnabled(true);
        enableProduct.setEnabled(true);
        
        productoCategory.setVisible(false); 
        categoriasCombo.setVisible(true);   
        productName.requestFocus();
    }//GEN-LAST:event_habilitarModificacion

    private void cancelAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAction
        if (!modificacion) return;
        
        modificacion = false;
        productName.setEnabled(false);
        productPrice.setEnabled(false);
        minStock.setEnabled(false);
        enableProduct.setEnabled(false);
        
        productoCategory.setVisible(true);  
        categoriasCombo.setVisible(false);  
        
        setProductData(producto); 
    }//GEN-LAST:event_cancelAction

    private void confirmarAciton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarAciton
        if (!modificacion) return;
        
        modificacion = false;
        productName.setEnabled(false);
        productPrice.setEnabled(false);
        minStock.setEnabled(false);
        enableProduct.setEnabled(false);
        
        productoCategory.setVisible(true);
        categoriasCombo.setVisible(false);
        
        // Recoger datos
        String nombreProd = productName.getText();
        double precioProd;
        int minStockProd;
        
        try {
            precioProd = Double.parseDouble(productPrice.getText().replace(",", "."));
            minStockProd = Integer.parseInt(minStock.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en el formato de números", "Error", JOptionPane.ERROR_MESSAGE);
            cancelAction(null);
            return;
        }

        String nombreCat = String.valueOf(categoriasCombo.getSelectedItem());
        
        // --- ACTUALIZACIÓN EN MEMORIA (SIMPLIFICADA) ---
        // Al ser un objeto directo, simplemente actualizamos el nombre de la categoría del objeto
        if (producto.getCategoria() != null) {
            producto.getCategoria().setNombre(nombreCat);
        } else {
            // Si por algún motivo venía nulo (raro con tu nueva BBDD), le creamos una dummy
            producto.setCategoria(new Categoria(0, nombreCat));
        }
        
        // Copia para la lista
        Producto prodAntiguo = producto.toBuilder().build(); 
        
        // Actualizar objeto principal
        producto.setNombre(nombreProd);
        producto.setPrecio(precioProd);
        producto.setMinStock(minStockProd);
        producto.setActivo(enableProduct.isSelected());
        
        // Enviar a la Base de Datos (Ahora es update directo)
        ProductoDAO.updateProduct(
            producto.getId(),
            producto.getNombre(),
            producto.getPrecio(),
            producto.getMinStock(),
            nombreCat,
            enableProduct.isSelected()
        );
        
        setProductData(producto);
        inventario.updateProductosOnUpdate(prodAntiguo, producto);
    }//GEN-LAST:event_confirmarAciton

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ProductoInfoDialog dialog = new ProductoInfoDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    
    // GETTER Y SETTER
    private void setDialogTitle(Producto producto) {
        tituloDialog.setText("Información de " + producto.getNombre());
    }
    
    private void setProductData(Producto producto) {
        productId.setText(String.valueOf(producto.getId()));
        productName.setText(producto.getNombre());
        productPrice.setText(String.valueOf(producto.getPrecio()));
        currentStock.setText(String.valueOf(producto.getStock()));
        minStock.setText(String.valueOf(producto.getMinStock()));
        
        if (producto.getCategoria() != null) {
            String nombreCategoria = producto.getCategoria().getNombre();
            categoriasCombo.setSelectedItem(nombreCategoria);
            productoCategory.setText(nombreCategoria);
        } else {
            productoCategory.setText(""); 
        }
        
        if (producto.isActivo()) {
            enableProduct.setSelected(producto.isActivo());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> categoriasCombo;
    private javax.swing.JTextField currentStock;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JCheckBox enableProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField minStock;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JTextField productId;
    private javax.swing.JLabel productImage;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productPrice;
    private javax.swing.JTextField productoCategory;
    private javax.swing.JLabel tituloDialog;
    // End of variables declaration//GEN-END:variables
}
