/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.promociones.items;

/**
 *
 * @author navas
 */
public class itemPromocionConcurrente extends javax.swing.JPanel {

    /**
     * Creates new form PromocionItem
     */
    public itemPromocionConcurrente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        promocionLbl = new javax.swing.JLabel();
        vigenciaLbl = new javax.swing.JLabel();
        activarpromoCheckBox = new javax.swing.JCheckBox();

        setOpaque(false);

        promocionLbl.setBackground(new java.awt.Color(255, 255, 255));
        promocionLbl.setForeground(new java.awt.Color(0, 0, 0));
        promocionLbl.setText("Promoción Navidad-Pescado2x1");
        promocionLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        promocionLbl.setOpaque(true);
        add(promocionLbl);

        vigenciaLbl.setBackground(new java.awt.Color(255, 255, 255));
        vigenciaLbl.setForeground(new java.awt.Color(0, 0, 0));
        vigenciaLbl.setText("Vigencia");
        vigenciaLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vigenciaLbl.setOpaque(true);
        add(vigenciaLbl);

        activarpromoCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        activarpromoCheckBox.setText("¿Activar?");
        add(activarpromoCheckBox);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activarpromoCheckBox;
    private javax.swing.JLabel promocionLbl;
    private javax.swing.JLabel vigenciaLbl;
    // End of variables declaration//GEN-END:variables
}
