/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boquerontech.supermercadoboqueron.informes.items;

/**
 *
 * @author navas
 */
public class ItemGestiondeProductos extends javax.swing.JPanel {

    /**
     * Creates new form itemGestiondeProductos
     */
    public ItemGestiondeProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        productoLbl = new javax.swing.JLabel();
        categoriaLbl = new javax.swing.JLabel();
        precioLbl = new javax.swing.JLabel();
        stockLbl = new javax.swing.JLabel();
        proveedorLbl = new javax.swing.JLabel();
        numVentasLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 253, 253));
        setForeground(new java.awt.Color(0, 0, 0));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        productoLbl.setBackground(new java.awt.Color(255, 255, 255));
        productoLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        productoLbl.setForeground(new java.awt.Color(0, 0, 0));
        productoLbl.setText("Producto");
        productoLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        productoLbl.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        add(productoLbl, gridBagConstraints);

        categoriaLbl.setBackground(new java.awt.Color(255, 255, 255));
        categoriaLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        categoriaLbl.setForeground(new java.awt.Color(0, 0, 0));
        categoriaLbl.setText("Categoria");
        categoriaLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        categoriaLbl.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        add(categoriaLbl, gridBagConstraints);

        precioLbl.setBackground(new java.awt.Color(255, 255, 255));
        precioLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        precioLbl.setForeground(new java.awt.Color(0, 0, 0));
        precioLbl.setText("Precio");
        precioLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        precioLbl.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        add(precioLbl, gridBagConstraints);

        stockLbl.setBackground(new java.awt.Color(255, 255, 255));
        stockLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        stockLbl.setForeground(new java.awt.Color(0, 0, 0));
        stockLbl.setText("Stock");
        stockLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stockLbl.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        add(stockLbl, gridBagConstraints);

        proveedorLbl.setBackground(new java.awt.Color(255, 255, 255));
        proveedorLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        proveedorLbl.setForeground(new java.awt.Color(0, 0, 0));
        proveedorLbl.setText("Proveedor");
        proveedorLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        proveedorLbl.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        add(proveedorLbl, gridBagConstraints);

        numVentasLbl.setBackground(new java.awt.Color(255, 255, 255));
        numVentasLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        numVentasLbl.setForeground(new java.awt.Color(0, 0, 0));
        numVentasLbl.setText("Nº Ventas");
        numVentasLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numVentasLbl.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 20);
        add(numVentasLbl, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public void setCategoria(String categoria) {
        categoriaLbl.setText(categoria);
    }
    public void setNumVentas(String numVentas) {
        numVentasLbl.setText(numVentas);
    }
    public void setPrecio(String precio) {
        precioLbl.setText(precio);
    }
    public void setProducto(String producto) {
        productoLbl.setText(producto);
    }
    public void setProveedor(String proveedor) {
        proveedorLbl.setText(proveedor);
    }
    public void setStock(String stock) {
        stockLbl.setText(stock);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoriaLbl;
    private javax.swing.JLabel numVentasLbl;
    private javax.swing.JLabel precioLbl;
    private javax.swing.JLabel productoLbl;
    private javax.swing.JLabel proveedorLbl;
    private javax.swing.JLabel stockLbl;
    // End of variables declaration//GEN-END:variables
}
