/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.boquerontech.supermercadoboqueron;

import com.boquerontech.supermercadoboqueron.promociones.InicioPromoP;
import com.boquerontech.supermercadoboqueron.inventario.Inventario;
import com.boquerontech.supermercadoboqueron.clientes.GestionClientes;
import com.boquerontech.supermercadoboqueron.database.DDBBConnector;
import com.boquerontech.supermercadoboqueron.empleados.GestionEmpleado;
import com.boquerontech.supermercadoboqueron.informes.InicioDocumentos;
import com.boquerontech.supermercadoboqueron.proveedores.Proveedores;
import com.formdev.flatlaf.FlatLightLaf;
import com.boquerontech.supermercadoboqueron.ventas.Ventas;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Adrian
 */
public class Inicio extends javax.swing.JFrame {
    // Instancia privada para el singleton
    private static Inicio inicioInstance;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());

    /**
     * Creates new form InicioBotones
     */
    private Inicio() {
        initComponents();
        setExtendedState(Inicio.MAXIMIZED_BOTH);
        colocarPanel(new pnlInicio());
        seleccionarBoton(btnInicio);
    }
    
    private Inicio(String user, String password) {
        initComponents();
        setExtendedState(Inicio.MAXIMIZED_BOTH);
        colocarPanel(new pnlInicio());
        seleccionarBoton(btnInicio);
    }
    
    // SINGLETON
    public static Inicio getInstance() {
        if (inicioInstance == null) {
            inicioInstance = new Inicio();
        }
        return inicioInstance;
    }
    
    public static Inicio getInstance(String user, String password) {
        if (inicioInstance == null) {
            inicioInstance = new Inicio(user, password);
        }
        return inicioInstance;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnPromociones = new javax.swing.JButton();
        btnDocumentos = new javax.swing.JButton();
        contenidoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                windowClosedAction(evt);
            }
        });

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 220, 215)));
        pnlMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        pnlMain.add(btnInicio);

        btnClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorderPainted(false);
        btnClientes.setContentAreaFilled(false);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setFocusPainted(false);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        pnlMain.add(btnClientes);

        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setBorderPainted(false);
        btnEmpleados.setContentAreaFilled(false);
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleados.setFocusPainted(false);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        pnlMain.add(btnEmpleados);

        btnVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setBorderPainted(false);
        btnVentas.setContentAreaFilled(false);
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.setFocusPainted(false);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        pnlMain.add(btnVentas);

        btnInventario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setBorderPainted(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.setFocusPainted(false);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        pnlMain.add(btnInventario);

        btnProveedores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setBorderPainted(false);
        btnProveedores.setContentAreaFilled(false);
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores.setFocusPainted(false);
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        pnlMain.add(btnProveedores);

        btnPromociones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPromociones.setText("Promociones");
        btnPromociones.setBorderPainted(false);
        btnPromociones.setContentAreaFilled(false);
        btnPromociones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPromociones.setFocusPainted(false);
        btnPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromocionesActionPerformed(evt);
            }
        });
        pnlMain.add(btnPromociones);

        btnDocumentos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDocumentos.setText("Documentos");
        btnDocumentos.setBorderPainted(false);
        btnDocumentos.setContentAreaFilled(false);
        btnDocumentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDocumentos.setFocusPainted(false);
        btnDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentosActionPerformed(evt);
            }
        });
        pnlMain.add(btnDocumentos);

        getContentPane().add(pnlMain, java.awt.BorderLayout.PAGE_START);

        contenidoPanel.setMinimumSize(new java.awt.Dimension(900, 900));
        contenidoPanel.setPreferredSize(new java.awt.Dimension(900, 900));
        contenidoPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(contenidoPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        colocarPanel(new GestionEmpleado());
        seleccionarBoton(btnEmpleados);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        colocarPanel(new pnlInicio());
        seleccionarBoton(btnInicio);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        colocarPanel(new GestionClientes());
        seleccionarBoton(btnClientes);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        colocarPanel(new Ventas());
        seleccionarBoton(btnVentas);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        colocarPanel(new Inventario());
        seleccionarBoton(btnInventario);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        colocarPanel(new Proveedores(this));
        seleccionarBoton(btnProveedores);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromocionesActionPerformed
        colocarPanel(new InicioPromoP(this));
        seleccionarBoton(btnPromociones);
    }//GEN-LAST:event_btnPromocionesActionPerformed

    private void btnDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentosActionPerformed
        colocarPanel(new InicioDocumentos(this));
        seleccionarBoton(btnDocumentos);
    }//GEN-LAST:event_btnDocumentosActionPerformed

    private void windowClosedAction(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosedAction
        DDBBConnector.shutdown();
    }//GEN-LAST:event_windowClosedAction

    public void colocarPanel(JPanel panel) {
        contenidoPanel.removeAll();
        contenidoPanel.add(panel, BorderLayout.CENTER);
        contenidoPanel.revalidate();
        contenidoPanel.repaint();
    }
    
    private JButton botonActivo = null; // variable para saber cuál está seleccionado

    private void seleccionarBoton(JButton boton) {
        if (botonActivo != null) {
            // Quitar “selección” del botón anterior
            botonActivo.setForeground(Color.BLACK);
        }
        // Marcar el nuevo botón como activo
        botonActivo = boton;
        botonActivo.setForeground(Color.BLUE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> Inicio.getInstance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDocumentos;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnPromociones;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnVentas;
    private javax.swing.JPanel contenidoPanel;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
